/* Generated by hyprconf from Omarchy's active theme — do not edit: the
   theme-set hook rewrites this on every `omarchy theme set`. */
/* What this is and how it gets here: modules/firefox-theme/README.md. */
:root {
  /* The mode Omarchy resolved for the theme (omarchy-theme-color:120-133),
     read back by the hook — it picks the built-in theme id and
     ui.systemUsesDarkTheme from this line. */
  --hyprconf-theme-mode: {{ mode }};
  /* The three theme variables Firefox 155.0.1-1 still reads outside a
     :root[lwtheme] block: --toolbar-field-background-color
     (urlbar/urlbar.tokens.css:13, urlbar-searchbar.css:1145),
     --toolbar-field-focus-color (smartbar.css:43) and
     --focus-outline-color (23 stylesheets). No --lwt-*: README > Settings. */
  --toolbar-field-background-color: {{ dark_background }} !important;
  --toolbar-field-focus-color: {{ foreground }} !important;
  --focus-outline-color: {{ accent }} !important;
}
/* The chrome itself, by the ids Firefox has kept stable for years — paints
   the same colours even when the user later picks another theme (or none),
   when the variables above would go unused. */
#navigator-toolbox, #TabsToolbar, #nav-bar, #PersonalToolbar {
  background-color: {{ background }} !important;
  color: {{ foreground }} !important;
}
#urlbar-background, #searchbar {
  background-color: {{ dark_background }} !important;
}
.tab-background[selected] {
  background-color: {{ lighter_background }} !important;
}
#sidebar-box, #sidebar-main {
  background-color: {{ background }} !important;
  color: {{ foreground }} !important;
}
