"""hyprconf.firefox_theme — palette-matched Firefox chrome from Omarchy's theme.

Omarchy 4.0.0-1 themes Chromium-family browsers only: omarchy-theme-set-browser
writes a managed-policy ``BrowserThemeColor`` for chromium/chrome/edge/brave and
nothing for Firefox (checked: ``grep -il firefox /usr/share/omarchy/bin/*``
finds no theming). This is the overlay's own bridge, run from the theme-set
hook after every ``omarchy theme set`` (``hooks/theme-set.d/10-hyprconf``).

It ports what hyprconf's retired theme engine did: a ``userChrome.css`` on
Firefox's stable ``--lwt-*`` / ``--toolbar-*`` lightweight-theme variables,
coloured from the ``colors.toml`` Omarchy renders for the active theme, plus
the ``user.js`` prefs that make Firefox load it and follow the theme's mode.
LibreWolf is a Firefox fork with the same profile layout, so it gets the same
treatment when present.

Firefox reads ``userChrome.css`` at startup only — there is no live restyle
IPC — so the chrome recolours on the next launch. The system policy the
installer ships (``infra/firefox/policies.json``) is unrelated and untouched.
"""

from __future__ import annotations

import argparse
import configparser
import os
import shutil
import subprocess
import sys
import tomllib
from pathlib import Path

# Every profiles.ini Firefox and LibreWolf may keep (legacy, then XDG — modern
# Arch Firefox uses the XDG one).
BROWSER_INIS = {
    "firefox": (".mozilla/firefox/profiles.ini", ".config/mozilla/firefox/profiles.ini"),
    "librewolf": (".librewolf/profiles.ini", ".config/librewolf/profiles.ini"),
}

COLORS_TOML_REL = ".local/state/omarchy/current/theme/colors.toml"

HEADER = (
    "/* Generated by hyprconf from Omarchy's active theme — do not edit: the\n"
    "   theme-set hook rewrites this on every `omarchy theme set`. */\n"
)

DEFAULT_PALETTE = {
    "mode": "dark",
    "background": "#1e1e2e",
    "foreground": "#cdd6f4",
    "accent": "#89b4fa",
    "muted": "#585b70",
    "selection": "#313244",
    "dark_background": "#181825",
    "lighter_background": "#313244",
}


def profile_inis(home: Path) -> list[tuple[str, Path]]:
    """(browser, ini) for every profiles.ini that exists under *home*."""
    return [
        (browser, home / rel)
        for browser, rels in BROWSER_INIS.items()
        for rel in rels
        if (home / rel).is_file()
    ]


def default_profile(ini: Path) -> Path | None:
    """The default profile directory named by a Firefox-style profiles.ini.

    An ``[Install…]`` section's ``Default=`` names the profile the installed
    build last used and wins; failing that, a ``[Profile…]`` with ``Default=1``;
    failing that, the first profile listed. ``IsRelative=1`` paths are relative
    to the ini's directory.
    """
    parser = configparser.ConfigParser(interpolation=None)
    try:
        parser.read(ini, encoding="utf-8")
    except configparser.Error:
        return None

    def resolve(section: str, path: str) -> Path:
        if parser.get(section, "IsRelative", fallback="1") == "1":
            return ini.parent / path
        return Path(path)

    for section in parser.sections():
        if section.startswith("Install") and parser.has_option(section, "Default"):
            candidate = ini.parent / parser.get(section, "Default")
            if candidate.is_dir():
                return candidate
    for section in parser.sections():
        if section.startswith("Profile") and parser.get(section, "Default", fallback="") == "1":
            if parser.has_option(section, "Path"):
                return resolve(section, parser.get(section, "Path"))
    for section in parser.sections():
        if section.startswith("Profile") and parser.has_option(section, "Path"):
            return resolve(section, parser.get(section, "Path"))
    return None


def read_palette(colors_toml: Path) -> dict[str, str]:
    """Omarchy's rendered colors.toml, with defaults for anything a theme omits."""
    data = tomllib.loads(colors_toml.read_text(encoding="utf-8"))
    palette = dict(DEFAULT_PALETTE)
    for key in palette:
        value = data.get(key)
        if isinstance(value, str) and value.strip():
            palette[key] = value.strip()
    return palette


def render_userchrome(palette: dict[str, str]) -> str:
    """The lightweight-theme variables, from Omarchy's semantic roles.

    Only the variables the retired engine used, plus the sidebar pair: these
    are the ones Firefox documents as its theming API, so they survive Firefox
    releases that reshuffle the internal chrome.
    """
    bg = palette["background"]
    fg = palette["foreground"]
    field = palette["dark_background"]
    raised = palette["lighter_background"]
    return (
        HEADER + ":root {\n"
        f"  --lwt-accent-color: {bg} !important;\n"
        f"  --lwt-text-color: {fg} !important;\n"
        f"  --toolbar-bgcolor: {bg} !important;\n"
        f"  --toolbar-color: {fg} !important;\n"
        f"  --tab-selected-bgcolor: {raised} !important;\n"
        f"  --toolbar-field-background-color: {field} !important;\n"
        f"  --toolbar-field-color: {fg} !important;\n"
        f"  --toolbar-field-focus-background-color: {field} !important;\n"
        f"  --toolbar-field-focus-color: {fg} !important;\n"
        f"  --lwt-sidebar-background-color: {bg} !important;\n"
        f"  --lwt-sidebar-text-color: {fg} !important;\n"
        f"  --focus-outline-color: {palette['accent']} !important;\n"
        "}\n"
    )


def theme_prefs(mode: str) -> dict[str, object]:
    """user.js prefs the stylesheet needs, plus the theme's light/dark mode.

    ``ui.systemUsesDarkTheme`` is what Firefox consults for prefers-color-scheme
    when it does not trust the desktop's answer; the two ``browser.theme.*``
    prefs pin the built-in light/dark theme's chrome and content to the same
    side so a light page never sits under a dark toolbar (0 = dark, 1 = light).
    """
    dark = mode != "light"
    return {
        "toolkit.legacyUserProfileCustomizations.stylesheets": True,
        "ui.systemUsesDarkTheme": 1 if dark else 0,
        "browser.theme.content-theme": 0 if dark else 1,
        "browser.theme.toolbar-theme": 0 if dark else 1,
    }


def format_pref(key: str, value: object) -> str:
    if isinstance(value, bool):
        literal = "true" if value else "false"
    elif isinstance(value, (int, float)):
        literal = str(value)
    else:
        literal = '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'
    return f'user_pref("{key}", {literal});'


def _pref_key(line: str) -> str | None:
    stripped = line.strip()
    if not stripped.startswith("user_pref("):
        return None
    return stripped.split(",", 1)[0].split("(", 1)[1].strip().strip('"')


def _write_if_changed(path: Path, text: str) -> bool:
    """Write *text* to *path*; True when the file did not already say that."""
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.write_text(text, encoding="utf-8")
    return True


def merge_user_js(path: Path, prefs: dict[str, object]) -> bool:
    """Rewrite the managed prefs in *path*, keeping every other line as it is.

    Returns True when the file changed.
    """
    kept: list[str] = []
    if path.exists():
        for line in path.read_text(encoding="utf-8").splitlines():
            if _pref_key(line) in prefs:
                continue
            kept.append(line)
    kept.extend(format_pref(k, v) for k, v in prefs.items())
    return _write_if_changed(path, "\n".join(kept) + "\n")


def apply(profile: Path, palette: dict[str, str]) -> bool:
    """Write the stylesheet and prefs into one profile. True when anything changed."""
    chrome = profile / "chrome"
    chrome.mkdir(parents=True, exist_ok=True)
    changed = _write_if_changed(chrome / "userChrome.css", render_userchrome(palette))
    return merge_user_js(profile / "user.js", theme_prefs(palette["mode"])) or changed


def notify(message: str) -> None:
    """A desktop notification through Omarchy's own command, when there is one.

    Firefox only reads userChrome.css at startup, and a theme switch gives no
    other sign that the browser is now behind — this is the one place the
    user learns a restart is due. Silent when the command is absent (a TTY
    run, a test) or fails: cosmetic, never an error.
    """
    cmd = shutil.which("omarchy-notification-send")
    if cmd is None:
        return
    try:
        subprocess.run(
            [cmd, "Firefox theme", message], check=False, timeout=10, capture_output=True
        )
    except (OSError, subprocess.SubprocessError):
        pass


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python3 -m hyprconf.firefox_theme",
        description="Extend Omarchy's active theme to Firefox/LibreWolf profiles.",
    )
    parser.add_argument(
        "--colors",
        type=Path,
        default=None,
        help=f"colors.toml to read (default: ~/{COLORS_TOML_REL})",
    )
    args = parser.parse_args(argv)

    home = Path(os.environ.get("HOME", Path.home()))
    colors = args.colors or home / COLORS_TOML_REL
    if not colors.is_file():
        print(f"hyprconf firefox theme: no {colors} — is a theme active?", file=sys.stderr)
        return 1
    palette = read_palette(colors)

    applied = 0
    changed: list[str] = []
    for browser, ini in profile_inis(home):
        profile = default_profile(ini)
        if profile is None or not profile.is_dir():
            continue
        if apply(profile, palette):
            changed.append(browser)
        print(f"{browser}: {profile / 'chrome' / 'userChrome.css'} ({palette['mode']})")
        applied += 1
    if not applied:
        print("hyprconf firefox theme: no Firefox/LibreWolf profile found — nothing to do")
    elif changed:
        print(
            "restart "
            + " and ".join(changed)
            + " to see the new theme (userChrome.css loads at startup)"
        )
        notify("Restart " + " and ".join(changed) + " to apply the new theme")
    return 0


if __name__ == "__main__":  # pragma: no cover — exercised through the hook tests
    sys.exit(main())
