"""hyprconf.firefox_theme — palette-matched Firefox chrome from Omarchy's theme.

Omarchy 4.0.0-1 themes Chromium-family browsers only: omarchy-theme-set-browser
writes a managed-policy ``BrowserThemeColor`` for chromium/chrome/edge/brave and
nothing for Firefox (checked: ``grep -il firefox /usr/share/omarchy/bin/*``
finds no theming). This is the overlay's own bridge, run from the theme-set
hook after every ``omarchy theme set`` (``hooks/theme-set.d/10-hyprconf``).

It ports what hyprconf's retired theme engine did: a ``userChrome.css`` on
Firefox's stable ``--lwt-*`` / ``--toolbar-*`` lightweight-theme variables,
coloured from the ``colors.toml`` Omarchy renders for the active theme, plus
the ``user.js`` prefs that make Firefox load it and follow the theme's mode.
LibreWolf is a Firefox fork with the same profile layout, so it gets the same
treatment when present.

Verified on Firefox 154 (2026-08-24) with a throwaway headless profile carrying
exactly this ``user.js``: ``extensions.json`` came up with
``firefox-compact-dark@mozilla.org`` ``active=true`` and the default theme
``userDisabled`` — ``extensions.activeThemeID`` in user.js does select the
built-in theme.

Firefox reads ``userChrome.css`` at startup only — there is no live restyle
IPC — so the chrome recolours on the next launch. The system policy the
installer ships (``infra/firefox/policies.json``) is unrelated and untouched.
"""

from __future__ import annotations

import argparse
import configparser
import os
import re
import shutil
import subprocess
import sys
import tomllib
from pathlib import Path

# Every profiles.ini Firefox and LibreWolf may keep (legacy, then XDG — modern
# Arch Firefox uses the XDG one).
BROWSER_INIS = {
    "firefox": (".mozilla/firefox/profiles.ini", ".config/mozilla/firefox/profiles.ini"),
    "librewolf": (".librewolf/profiles.ini", ".config/librewolf/profiles.ini"),
}

COLORS_TOML_REL = ".local/state/omarchy/current/theme/colors.toml"

# Firefox's built-in Dark / Light themes. They are lightweight themes, and
# that is the whole point: Firefox applies ``--lwt-*`` / ``--toolbar-*``
# overrides only while a lightweight theme is active (``:root:-moz-lwtheme``
# in browser.css). Under the default "System theme — auto"
# (default-theme@mozilla.org) the same userChrome.css does nothing, which
# is exactly what a fresh profile runs — the retired engine activated one of
# these by ``extensions.activeThemeID`` for the same reason.
THEME_ID_DARK = "firefox-compact-dark@mozilla.org"
THEME_ID_LIGHT = "firefox-compact-light@mozilla.org"

# Prefs earlier hyprconf releases wrote and no longer manage. Firefox derives
# both from the active theme, so a stale copy left in user.js would win over
# the theme at every start (a light theme with dark toolbars). merge_user_js
# removes them; nothing else in Omarchy writes them.
RETIRED_PREFS = frozenset({"browser.theme.content-theme", "browser.theme.toolbar-theme"})

HEADER = (
    "/* Generated by hyprconf from Omarchy's active theme — do not edit: the\n"
    "   theme-set hook rewrites this on every `omarchy theme set`. */\n"
)

# Only the roles render_userchrome paints; anything else in colors.toml is
# left alone rather than carried around unused.
DEFAULT_PALETTE = {
    "mode": "dark",
    "background": "#1e1e2e",
    "foreground": "#cdd6f4",
    "accent": "#89b4fa",
    "dark_background": "#181825",
    "lighter_background": "#313244",
}

# A user_pref line, either quote style Firefox's parser accepts, split into
# key, the rest of the statement, and whatever trails the ``;`` (an inline
# ``//`` or ``/* */`` comment the user wrote — kept when the line is rewritten).
_PREF_RE = re.compile(
    r"""^\s*user_pref\(\s*(?P<q>["'])(?P<key>.*?)(?P=q)\s*,(?P<value>.*?)\)\s*;(?P<tail>\s*(?://|/\*).*)?$"""
)


def profile_inis(home: Path) -> list[tuple[str, Path]]:
    """(browser, ini) for every profiles.ini that exists under *home*."""
    return [
        (browser, home / rel)
        for browser, rels in BROWSER_INIS.items()
        for rel in rels
        if (home / rel).is_file()
    ]


def default_profiles(ini: Path) -> list[Path]:
    """The default profile directories a Firefox-style profiles.ini names.

    Firefox keys ``[Install<hash>]`` sections by the hash of its own install
    directory and honours only its own; two builds sharing one profiles.ini
    (say the package and a Developer Edition) each name their own profile, and
    there is no telling from here which will start next — so every distinct
    existing profile any ``[Install…]`` ``Default=`` names is returned. Only
    when none does: the ``[Profile…]`` with ``Default=1``, failing that the
    first profile listed. ``IsRelative=1`` paths are relative to the ini's
    directory.
    """
    parser = configparser.ConfigParser(interpolation=None)
    try:
        parser.read(ini, encoding="utf-8")
    except configparser.Error:
        return []

    def resolve(path: str, relative: bool) -> Path:
        return ini.parent / path if relative else Path(path)

    installed: dict[Path, None] = {}
    for section in parser.sections():
        if section.startswith("Install") and parser.has_option(section, "Default"):
            value = parser.get(section, "Default")
            candidate = resolve(value, not Path(value).is_absolute())
            if candidate.is_dir():
                installed.setdefault(candidate, None)
    if installed:
        return list(installed)
    profiles = [
        s for s in parser.sections() if s.startswith("Profile") and parser.has_option(s, "Path")
    ]
    flagged = [s for s in profiles if parser.get(s, "Default", fallback="") == "1"]
    return [
        resolve(parser.get(s, "Path"), parser.get(s, "IsRelative", fallback="1") == "1")
        for s in (flagged or profiles)[:1]
    ]


def read_palette(colors_toml: Path) -> dict[str, str]:
    """Omarchy's rendered colors.toml, with defaults for anything a theme omits."""
    data = tomllib.loads(colors_toml.read_text(encoding="utf-8"))
    palette = dict(DEFAULT_PALETTE)
    for key in palette:
        value = data.get(key)
        if isinstance(value, str) and value.strip():
            palette[key] = value.strip()
    return palette


def render_userchrome(palette: dict[str, str]) -> str:
    """The lightweight-theme variables, from Omarchy's semantic roles.

    Only the variables the retired engine used, plus the sidebar pair: these
    are the ones Firefox documents as its theming API, so they survive Firefox
    releases that reshuffle the internal chrome.
    """
    bg = palette["background"]
    fg = palette["foreground"]
    field = palette["dark_background"]
    raised = palette["lighter_background"]
    return (
        HEADER
        # The variables: Firefox's documented theming API, honoured under a
        # lightweight theme (theme_prefs activates the built-in one).
        + ":root {\n"
        f"  --lwt-accent-color: {bg} !important;\n"
        f"  --lwt-text-color: {fg} !important;\n"
        f"  --toolbar-bgcolor: {bg} !important;\n"
        f"  --toolbar-color: {fg} !important;\n"
        f"  --tab-selected-bgcolor: {raised} !important;\n"
        f"  --toolbar-field-background-color: {field} !important;\n"
        f"  --toolbar-field-color: {fg} !important;\n"
        f"  --toolbar-field-focus-background-color: {field} !important;\n"
        f"  --toolbar-field-focus-color: {fg} !important;\n"
        f"  --lwt-sidebar-background-color: {bg} !important;\n"
        f"  --lwt-sidebar-text-color: {fg} !important;\n"
        f"  --focus-outline-color: {palette['accent']} !important;\n"
        "}\n"
        # The chrome itself, by the ids Firefox has kept stable for years —
        # paints the same colours even when the user later picks another
        # theme (or none), when the variables above would go unused.
        "#navigator-toolbox, #TabsToolbar, #nav-bar, #PersonalToolbar {\n"
        f"  background-color: {bg} !important;\n"
        f"  color: {fg} !important;\n"
        "}\n"
        "#urlbar-background, #searchbar {\n"
        f"  background-color: {field} !important;\n"
        "}\n"
        ".tab-background[selected] {\n"
        f"  background-color: {raised} !important;\n"
        "}\n"
        "#sidebar-box, #sidebar-main {\n"
        f"  background-color: {bg} !important;\n"
        f"  color: {fg} !important;\n"
        "}\n"
    )


def theme_prefs(mode: str) -> dict[str, object]:
    """user.js prefs the stylesheet needs, plus the theme's light/dark mode.

    ``extensions.activeThemeID`` activates the built-in Dark or Light theme —
    the stylesheet's ``--lwt-*`` overrides only take effect under a lightweight
    theme, and a fresh profile runs the default (system) theme, under which
    the same file changes nothing (verified on Firefox 154, see the module
    docstring). ``ui.systemUsesDarkTheme`` is what Firefox consults for
    prefers-color-scheme when it does not trust the desktop's answer. The
    ``browser.theme.content-theme`` / ``toolbar-theme`` prefs are deliberately
    not set: Firefox writes them itself from the active theme, so they are
    outputs of the theme switch, not inputs to it.
    """
    dark = mode != "light"
    return {
        "toolkit.legacyUserProfileCustomizations.stylesheets": True,
        "extensions.activeThemeID": THEME_ID_DARK if dark else THEME_ID_LIGHT,
        "ui.systemUsesDarkTheme": 1 if dark else 0,
    }


def format_pref(key: str, value: object) -> str:
    if isinstance(value, bool):
        literal = "true" if value else "false"
    elif isinstance(value, (int, float)):
        literal = str(value)
    else:
        literal = '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'
    return f'user_pref("{key}", {literal});'


def _pref_key(line: str) -> str | None:
    """The key of a ``user_pref("…"| '…', …);`` line, either quote style."""
    m = _PREF_RE.match(line)
    return m.group("key") if m else None


def _read_raw(path: Path, errors: str = "strict") -> str:
    """The file as written, CRLF and all (read_text would fold it to LF)."""
    with path.open(encoding="utf-8", errors=errors, newline="") as fh:
        return fh.read()


def _write_if_changed(path: Path, text: str) -> bool:
    """Write *text* to *path* byte-for-byte; True when the file did not already say that."""
    if path.exists() and _read_raw(path) == text:
        return False
    path.write_text(text, encoding="utf-8", newline="")
    return True


def merge_user_js(path: Path, prefs: dict[str, object]) -> bool:
    """Rewrite the managed prefs in *path*, keeping every other line as it is.

    A managed pref already present is rewritten in place, its inline comment
    kept; later duplicates go; prefs not yet there are appended; a pref in
    RETIRED_PREFS (managed by an earlier release) is dropped. The file's own
    line ending (LF or CRLF) is preserved. Returns True when the file changed.
    """
    raw = _read_raw(path) if path.exists() else ""
    newline = "\r\n" if "\r\n" in raw else "\n"
    pending = dict(prefs)
    kept: list[str] = []
    for line in raw.splitlines():
        m = _PREF_RE.match(line)
        key = m.group("key") if m else None
        if key in RETIRED_PREFS:
            continue
        if key not in prefs:
            kept.append(line)
        elif key in pending:
            kept.append(format_pref(key, pending.pop(key)) + (m.group("tail") or ""))
    kept.extend(format_pref(k, v) for k, v in pending.items())
    return _write_if_changed(path, newline.join(kept) + newline)


def apply(profile: Path, palette: dict[str, str]) -> bool:
    """Write the stylesheet and prefs into one profile. True when anything changed."""
    chrome = profile / "chrome"
    chrome.mkdir(parents=True, exist_ok=True)
    changed = _write_if_changed(chrome / "userChrome.css", render_userchrome(palette))
    return merge_user_js(profile / "user.js", theme_prefs(palette["mode"])) or changed


def notify(message: str) -> None:
    """A desktop notification through Omarchy's own command, when there is one.

    Firefox only reads userChrome.css at startup, and a theme switch gives no
    other sign that the browser is now behind — this is the one place the
    user learns a restart is due. Silent when the command is absent (a TTY
    run, a test) or fails: cosmetic, never an error.
    """
    cmd = shutil.which("omarchy-notification-send")
    if cmd is None:
        return
    try:
        subprocess.run(
            [cmd, "Firefox theme", message], check=False, timeout=10, capture_output=True
        )
    except (OSError, subprocess.SubprocessError):
        pass


def _pref_value(path: Path, key: str) -> str | None:
    """The value Firefox last wrote for *key* into prefs.js (None when absent)."""
    if not path.exists():
        return None
    for line in _read_raw(path, errors="replace").splitlines():
        m = _PREF_RE.match(line)
        if m and m.group("key") == key:
            return m.group("value").strip().strip('"')
    return None


def _pref_key_present(path: Path, key: str) -> bool:
    return path.exists() and any(_pref_key(line) == key for line in _read_raw(path).splitlines())


def status(home: Path) -> int:
    """Say what is in place and — the usual question — whether Firefox has
    restarted since: prefs.js is rewritten by Firefox from its live state, so
    once it carries our activeThemeID, user.js has been read."""
    colors = home / COLORS_TOML_REL
    print(f"colors.toml: {'present' if colors.is_file() else 'MISSING'} ({colors})")
    wanted = None
    if colors.is_file():
        wanted = str(theme_prefs(read_palette(colors)["mode"])["extensions.activeThemeID"])
    managed = list(theme_prefs("dark"))
    found = False
    for browser, ini in profile_inis(home):
        profiles = [p for p in default_profiles(ini) if p.is_dir()]
        if not profiles:
            print(f"{browser}: {ini} names no usable default profile")
            continue
        found = True
        for profile in profiles:
            css = profile / "chrome" / "userChrome.css"
            js = profile / "user.js"
            print(f"{browser}: profile {profile}")
            print(f"  userChrome.css: {'written' if css.is_file() else 'MISSING'}")
            have = sum(1 for k in managed if _pref_key_present(js, k))
            print(f"  user.js: {have}/{len(managed)} managed prefs present")
            active = _pref_value(profile / "prefs.js", "extensions.activeThemeID")
            if wanted and active == wanted:
                print(f"  restarted since the files were written: yes (active theme {active})")
            else:
                print(
                    "  restarted since the files were written: NO — prefs.js says "
                    f"{active or 'nothing'}; close every Firefox window and start it again"
                )
    if not found:
        print("no Firefox/LibreWolf profile found under", home)
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python3 -m hyprconf.firefox_theme",
        description="Extend Omarchy's active theme to Firefox/LibreWolf profiles.",
    )
    parser.add_argument(
        "--status",
        action="store_true",
        help="report what is written where and whether Firefox has restarted since",
    )
    args = parser.parse_args(argv)

    home = Path(os.environ.get("HOME", Path.home()))
    if args.status:
        return status(home)
    colors = home / COLORS_TOML_REL
    if not colors.is_file():
        print(f"hyprconf firefox theme: no {colors} — is a theme active?", file=sys.stderr)
        return 1
    palette = read_palette(colors)

    applied = 0
    changed: dict[str, None] = {}  # browsers, in order, without repeats
    for browser, ini in profile_inis(home):
        for profile in default_profiles(ini):
            if not profile.is_dir():
                continue
            if apply(profile, palette):
                changed.setdefault(browser, None)
            print(f"{browser}: {profile / 'chrome' / 'userChrome.css'} ({palette['mode']})")
            applied += 1
    if not applied:
        print("hyprconf firefox theme: no Firefox/LibreWolf profile found — nothing to do")
    elif changed:
        print(
            "restart "
            + " and ".join(changed)
            + " to see the new theme (userChrome.css loads at startup)"
        )
        notify("Restart " + " and ".join(changed) + " to apply the new theme")
    return 0


if __name__ == "__main__":  # pragma: no cover — exercised through the hook tests
    sys.exit(main())
