# Wallpaper variable — updated by the theme switcher
$wallpaper = ~/wallpaper/gruvbox.jpg

wallpaper {
    monitor  = eDP-1
    path     = $wallpaper
    fit_mode = cover
}

wallpaper {
    monitor  = eDP-2
    path     = $wallpaper
    fit_mode = cover
}

wallpaper {
    monitor  = DP-1
    path     = $wallpaper
    fit_mode = cover
}

wallpaper {
    monitor  = DP-2
    path     = $wallpaper
    fit_mode = cover
}

wallpaper {
    monitor  = DP-3
    path     = $wallpaper
    fit_mode = cover
}

wallpaper {
    monitor  = HDMI-A-1
    path     = $wallpaper
    fit_mode = cover
}

wallpaper {
    monitor  = HDMI-A-2
    path     = $wallpaper
    fit_mode = cover
}

splash = false
ipc    = true
