monitorv2 {
    output       = DP-2
    mode         = 3840x2160@75
    position     = 0x0
    scale        = 2
    transform    = 3
    supports_hdr = true
}

monitorv2 {
    output       = DP-1
    mode         = 3840x2160@240
    position     = auto-left
    scale        = 2
    supports_hdr = true
}

monitorv2 {
    output       = HDMI-A-1
    mode         = 3840x2160@120
    position     = auto-left
    scale        = 2
    supports_hdr = true
}

workspace = 1, monitor:DP-1
workspace = 2, monitor:DP-1
workspace = 3, monitor:HDMI-A-1
workspace = 4, monitor:HDMI-A-1
workspace = 5, monitor:DP-2
workspace = 6, monitor:DP-2
