-- Generated by switch_theme.py — do not edit manually

hl.config({
    general = {
        col = {
            active_border = { colors = { "rgba(d65d0eee)", "rgba(8ec07cee)" }, angle = 45 },
            inactive_border = "rgba(928374aa)",
        },
    },
})
