-- Generated by switch_theme.py — do not edit manually

hl.config({
    general = {
        col = {
            active_border = { colors = { "rgba(8be9fdee)", "rgba(8be9fdee)" }, angle = 45 },
            inactive_border = "rgba(6272a4aa)",
        },
    },
})
