# Preload wallpapers
$wallpaper = dracula.png
preload = $wallpaper

# Apply wallpaper per output
wallpaper {
    monitor = eDP-1
    path = /home/andy/wallpaper/$wallpaper
    fit_mode = cover
}

wallpaper {
    monitor = eDP-2
    path = /home/andy/wallpaper/$wallpaper
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = /home/andy/wallpaper/$wallpaper
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/andy/wallpaper/$wallpaper
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = /home/andy/wallpaper/$wallpaper
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/andy/wallpaper/$wallpaper
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-2
    path = /home/andy/wallpaper/$wallpaper
    fit_mode = cover
}

# Optional: splash and IPC settings
splash = false
ipc = true

