preload=/home/andy/wallpaper/dracula.png
wallpaper=eDP-1,/home/andy/wallpaper/dracula.png
wallpaper=DP-1,/home/andy/wallpaper/dracula.png
wallpaper=DP-2,/home/andy/wallpaper/dracula.png
wallpaper=DP-3,/home/andy/wallpaper/dracula.png
wallpaper=HDMI-A-1,/home/andy/wallpaper/dracula.png
wallpaper=HDMI-A-2,/home/andy/wallpaper/dracula.png
