#!/usr/bin/env bash
#
#  infra/deploy.sh — idempotent AWS deploy for hyprconf
#
#  Invoked via:  hyprconf deploy
#  Or directly:  bash infra/deploy.sh
#
#  On first run, prompts interactively for all required settings and saves
#  them to ~/.config/hyprconf/infra.env (outside the repo, chmod 600).
#  Subsequent runs (and 'hyprconf deploy' refreshes) load from that file
#  without prompting, making the command fully idempotent.
#
#  For CI/CD or scripted use, export all required variables before calling
#  this script — it will skip the interactive prompts automatically.
#
#  Required variables (after interactive setup or manual export):
#    HYPRCONF_DOMAIN      — domain to serve install.sh (e.g. get.yourdomain.com)
#    HYPRCONF_BUCKET      — S3 bucket name (globally unique)
#    HYPRCONF_ZONE_ID     — Route53 hosted zone ID for parent domain
#
#  Optional:
#    HYPRCONF_REPO        — GitHub repo URL (auto-detected from git remote)
#    AWS_PROFILE          — named AWS profile
#    AWS_ACCESS_KEY_ID    — explicit credentials (alternative to profile)
#    AWS_SECRET_ACCESS_KEY
#    AWS_DEFAULT_REGION   — defaults to us-east-1 (required for CloudFront ACM)

set -euo pipefail

INFRA_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$INFRA_DIR")"

# Config and state live OUTSIDE the repo so they are never accidentally committed.
CFG_DIR="$HOME/.config/hyprconf"
CFG_FILE="$CFG_DIR/infra.env"
STATE_FILE="$CFG_DIR/deploy-state"

# ── Colour palette ────────────────────────────────────────────────────────────
if [[ -t 1 ]]; then
  WH=$'\e[1;37m' GL=$'\e[1;31m' AM=$'\e[1;33m'
  GR=$'\e[1;32m' DM=$'\e[2;37m' RS=$'\e[0m'
else
  WH='' GL='' AM='' GR='' DM='' RS=''
fi

log_step() { printf '%s  ▸ %s%s%s\n'        "$AM" "$WH" "$1" "$RS"; }
log_ok()   { printf '%s  ✔ %s%s%s\n'        "$GR" "$WH" "$1" "$RS"; }
log_warn() { printf '%s  ! %s%s%s\n'        "$AM" "$WH" "$1" "$RS"; }
log_info() { printf '%s  ─ %s%s%s\n'        "$DM" "$WH" "$1" "$RS"; }
log_die()  { printf '%s  ✘ FATAL: %s%s%s\n' "$GL" "$WH" "$1" "$RS" >&2; exit 1; }
log_head() { printf '\n%s  ── %s ─%s\n\n'   "$DM" "$1" "$RS"; }

# ── State helpers ─────────────────────────────────────────────────────────────
state_get() { grep "^${1}=" "$STATE_FILE" 2>/dev/null | cut -d= -f2- || true; }
state_set() {
  mkdir -p "$CFG_DIR"
  touch "$STATE_FILE"
  if grep -q "^${1}=" "$STATE_FILE" 2>/dev/null; then
    sed -i "s|^${1}=.*|${1}=${2}|" "$STATE_FILE"
  else
    printf '%s=%s\n' "$1" "$2" >> "$STATE_FILE"
  fi
}

# ── Interactive prompt helper ─────────────────────────────────────────────────
# _ask VAR "Label" ["default"]  — reads input, keeps existing/default if blank
_ask() {
  local var="$1" label="$2" default="${3:-}"
  local current="${!var:-}"
  local hint=""
  [[ -n "$current" ]] && hint=" [${current}]" || { [[ -n "$default" ]] && hint=" [${default}]"; }
  printf '%s  %s%s%s: ' "$DM" "$WH" "${label}${hint}" "$RS"
  local input; read -r input
  input="${input:-${current:-$default}}"
  [[ -n "$input" ]] || { printf '%s  Value required.%s\n' "$GL" "$RS"; return 1; }
  printf -v "$var" '%s' "$input"
  export "${var?}"
}

# _ask_secret — like _ask but hides input (for credentials)
_ask_secret() {
  local var="$1" label="$2"
  printf '%s  %s%s (hidden)%s: ' "$DM" "$WH" "$label" "$RS"
  local input; read -rs input; printf '\n'
  [[ -n "$input" ]] || { printf '%s  Value required.%s\n' "$GL" "$RS"; return 1; }
  printf -v "$var" '%s' "$input"
  export "${var?}"
}

# ── Save config file ──────────────────────────────────────────────────────────
_save_config() {
  mkdir -p "$CFG_DIR"
  ( umask 077
    printf '# hyprconf deployment configuration\n'
    printf '# Generated by: hyprconf deploy\n'
    printf '# To reconfigure: delete this file and re-run hyprconf deploy\n'
    printf '# KEEP THIS FILE PRIVATE — it may contain AWS credentials.\n\n'
    [[ -n "${AWS_PROFILE:-}"             ]] && printf 'export AWS_PROFILE="%s"\n'             "$AWS_PROFILE"
    [[ -n "${AWS_ACCESS_KEY_ID:-}"       ]] && printf 'export AWS_ACCESS_KEY_ID="%s"\n'       "$AWS_ACCESS_KEY_ID"
    [[ -n "${AWS_SECRET_ACCESS_KEY:-}"   ]] && printf 'export AWS_SECRET_ACCESS_KEY="%s"\n'   "$AWS_SECRET_ACCESS_KEY"
    [[ -n "${AWS_SESSION_TOKEN:-}"       ]] && printf 'export AWS_SESSION_TOKEN="%s"\n'       "$AWS_SESSION_TOKEN"
    printf 'export AWS_DEFAULT_REGION="%s"\n'  "${AWS_DEFAULT_REGION:-us-east-1}"
    printf '\n'
    printf 'export HYPRCONF_DOMAIN="%s"\n'     "$HYPRCONF_DOMAIN"
    printf 'export HYPRCONF_BUCKET="%s"\n'     "$HYPRCONF_BUCKET"
    printf 'export HYPRCONF_ZONE_ID="%s"\n'    "$HYPRCONF_ZONE_ID"
    printf 'export HYPRCONF_REPO="%s"\n'       "${HYPRCONF_REPO:-}"
  ) > "$CFG_FILE"
  log_ok "Config saved → $CFG_FILE"
}

# ── AWS authentication setup ──────────────────────────────────────────────────
_configure_aws() {
  if aws sts get-caller-identity &>/dev/null 2>&1; then
    log_ok "AWS credentials already valid."
    return 0
  fi

  printf '\n%s  [ AWS Authentication ]%s\n' "$AM" "$RS"
  printf '%s  1) Named profile (recommended — uses ~/.aws/config)\n' "$DM"
  printf '  2) Access key + secret (for accounts without local AWS config)%s\n' "$RS"
  printf '%s  Choice [1]: %s' "$WH" "$RS"
  local choice; read -r choice; choice="${choice:-1}"

  if [[ "$choice" == "2" ]]; then
    _ask        AWS_ACCESS_KEY_ID     "Access Key ID"
    _ask_secret AWS_SECRET_ACCESS_KEY "Secret Access Key"
    printf '%s  Session Token%s (press Enter to skip): ' "$DM$WH" "$DM"
    local tok; read -rs tok; printf '\n'
    [[ -n "$tok" ]] && { AWS_SESSION_TOKEN="$tok"; export AWS_SESSION_TOKEN; }
  else
    _ask AWS_PROFILE "AWS profile name" "default"
  fi

  aws sts get-caller-identity &>/dev/null 2>&1 \
    || log_die "AWS authentication failed. Check your credentials and try again."
  log_ok "AWS credentials valid."
}

# ── Route53 zone selection ────────────────────────────────────────────────────
_select_zone() {
  log_step "Fetching Route53 hosted zones..."

  local zones_raw
  zones_raw=$(aws route53 list-hosted-zones \
    --query 'HostedZones[].[Name,Id]' --output text 2>/dev/null) || {
    log_warn "Could not list hosted zones. Enter your Zone ID manually."
    _ask HYPRCONF_ZONE_ID "Route53 Hosted Zone ID"
    return
  }

  if [[ -z "$zones_raw" ]]; then
    log_warn "No hosted zones found in this AWS account."
    _ask HYPRCONF_ZONE_ID "Route53 Hosted Zone ID"
    return
  fi

  local names=() ids=()
  while IFS=$'\t' read -r name id; do
    names+=("${name%.}")               # strip trailing dot
    ids+=("${id##*/hostedzone/}")      # extract ID from /hostedzone/XXXX
  done <<< "$zones_raw"

  # Try to auto-match: find any zone whose name the domain ends with
  local match_idx=-1
  for i in "${!names[@]}"; do
    if [[ "$HYPRCONF_DOMAIN" == *.${names[$i]} ]] || \
       [[ "$HYPRCONF_DOMAIN" == "${names[$i]}" ]]; then
      match_idx=$i
    fi
  done

  if [[ $match_idx -ge 0 ]]; then
    printf '%s  Auto-matched zone: %s%s%s  (%s)\n' \
      "$GR" "$WH" "${names[$match_idx]}" "$RS" "${ids[$match_idx]}"
    printf '%s  Use this zone? [Y/n]: %s' "$DM$WH" "$RS"
    local yn; read -r yn
    if [[ "${yn,,}" != "n" ]]; then
      HYPRCONF_ZONE_ID="${ids[$match_idx]}"; export HYPRCONF_ZONE_ID
      return
    fi
  fi

  # Show menu
  printf '\n%s  Available hosted zones:%s\n' "$AM" "$RS"
  for i in "${!names[@]}"; do
    printf '%s  %2d)  %-35s %s%s\n' "$DM" $((i+1)) "${names[$i]}" "${ids[$i]}" "$RS"
  done
  printf '%s  Select zone number: %s' "$WH" "$RS"
  local sel; read -r sel
  local idx=$(( sel - 1 ))
  [[ $idx -ge 0 && $idx -lt ${#ids[@]} ]] \
    || log_die "Invalid selection."
  HYPRCONF_ZONE_ID="${ids[$idx]}"; export HYPRCONF_ZONE_ID
}

# ── Interactive environment configuration ─────────────────────────────────────
configure_env() {
  # Load saved config if present (vars already in env take priority)
  [[ -f "$CFG_FILE" ]] && source "$CFG_FILE"

  # If everything is already configured, skip all prompts
  if [[ -n "${HYPRCONF_DOMAIN:-}"   ]] && \
     [[ -n "${HYPRCONF_BUCKET:-}"   ]] && \
     [[ -n "${HYPRCONF_ZONE_ID:-}"  ]] && \
     aws sts get-caller-identity &>/dev/null 2>&1; then
    log_ok "Config loaded from $CFG_FILE"
    return 0
  fi

  [[ -t 0 ]] \
    || log_die "Configuration incomplete and no interactive terminal available.
       Export required variables or run 'hyprconf deploy' interactively."

  log_head "hyprconf deploy — first-time setup"
  printf '%s  Settings will be saved to: %s%s%s\n\n' \
    "$DM" "$WH" "$CFG_FILE" "$RS"

  command -v aws &>/dev/null \
    || log_die "AWS CLI not found. Install: https://aws.amazon.com/cli/"

  # AWS credentials
  _configure_aws

  # Region
  printf '\n%s  [ Region ]%s\n' "$AM" "$RS"
  printf '%s  Must be us-east-1 for CloudFront ACM certificates.%s\n' "$DM" "$RS"
  _ask AWS_DEFAULT_REGION "AWS region" "us-east-1"

  # Domain
  printf '\n%s  [ Install Domain ]%s\n' "$AM" "$RS"
  printf '%s  The domain where your install.sh will be served over HTTPS.\n' "$DM"
  printf '  Example: get.yourdomain.com%s\n' "$RS"
  while [[ -z "${HYPRCONF_DOMAIN:-}" ]]; do
    _ask HYPRCONF_DOMAIN "Domain"
  done

  # S3 bucket (suggest from domain)
  printf '\n%s  [ S3 Bucket ]%s\n' "$AM" "$RS"
  local suggested_bucket; suggested_bucket=$(printf '%s' "$HYPRCONF_DOMAIN" | tr '.' '-')
  _ask HYPRCONF_BUCKET "S3 bucket name (must be globally unique)" "$suggested_bucket"

  # Route53 zone
  printf '\n%s  [ Route53 Hosted Zone ]%s\n' "$AM" "$RS"
  if [[ -z "${HYPRCONF_ZONE_ID:-}" ]]; then
    _select_zone
  else
    log_ok "Zone ID already set: $HYPRCONF_ZONE_ID"
  fi

  # GitHub repo
  printf '\n%s  [ Repository URL ]%s\n' "$AM" "$RS"
  printf '%s  The repo cloned by your install.sh bootstrap.%s\n' "$DM" "$RS"
  local detected_repo
  detected_repo=$(git -C "$ROOT_DIR" remote get-url origin 2>/dev/null \
    | sed 's|^git@github\.com:|https://github.com/|; s|\.git$||' || true)
  _ask HYPRCONF_REPO "GitHub repo URL" "$detected_repo"

  printf '\n'
  _save_config
}

# ── Step 1: S3 bucket + install.sh upload ─────────────────────────────────────
deploy_bucket() {
  log_head "S3"

  if ! aws s3api head-bucket --bucket "$HYPRCONF_BUCKET" 2>/dev/null; then
    log_step "Creating bucket $HYPRCONF_BUCKET ..."
    local args=(--bucket "$HYPRCONF_BUCKET")
    [[ "${AWS_DEFAULT_REGION:-us-east-1}" != "us-east-1" ]] && \
      args+=(--create-bucket-configuration "LocationConstraint=${AWS_DEFAULT_REGION}")
    aws s3api create-bucket "${args[@]}" --output text > /dev/null
    log_ok "Bucket created."
  else
    log_ok "Bucket exists."
  fi

  # Allow bucket policy to grant public read on install.sh
  aws s3api put-public-access-block --bucket "$HYPRCONF_BUCKET" \
    --public-access-block-configuration \
    'BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false' \
    > /dev/null

  aws s3api put-bucket-policy --bucket "$HYPRCONF_BUCKET" --policy "{
    \"Version\": \"2012-10-17\",
    \"Statement\": [{
      \"Sid\": \"PublicReadInstallScript\",
      \"Effect\": \"Allow\",
      \"Principal\": \"*\",
      \"Action\": \"s3:GetObject\",
      \"Resource\": \"arn:aws:s3:::${HYPRCONF_BUCKET}/install.sh\"
    }]
  }" > /dev/null

  # Inject this fork's repo URL into install.sh before uploading.
  # The source file keeps the original URL; the deployed copy uses HYPRCONF_REPO.
  log_step "Uploading install.sh (repo: ${HYPRCONF_REPO}) ..."
  local tmp; tmp=$(mktemp)
  sed "s|^readonly REPO_URL=.*|readonly REPO_URL=\"${HYPRCONF_REPO}\"|" \
    "$ROOT_DIR/install/install.sh" > "$tmp"
  aws s3 cp "$tmp" "s3://$HYPRCONF_BUCKET/install.sh" \
    --content-type 'text/plain; charset=utf-8' \
    --cache-control 'no-cache, no-store' \
    --output text > /dev/null
  rm -f "$tmp"
  log_ok "install.sh uploaded → s3://$HYPRCONF_BUCKET/install.sh"
}

# ── Step 2: ACM certificate (us-east-1 only) ──────────────────────────────────
deploy_cert() {
  log_head "ACM Certificate"

  local cert_arn; cert_arn="$(state_get CERT_ARN)"

  if [[ -n "$cert_arn" ]]; then
    local status
    status=$(aws acm describe-certificate --certificate-arn "$cert_arn" \
      --region us-east-1 --query 'Certificate.Status' --output text 2>/dev/null || true)
    if [[ "$status" == "ISSUED" ]]; then
      log_ok "Certificate already issued: $cert_arn"; return 0
    elif [[ "$status" == "PENDING_VALIDATION" ]]; then
      log_step "Certificate pending — attempting to auto-validate via Route53 ..."
      _upsert_cert_cname "$cert_arn"
      _wait_cert_issued "$cert_arn"
      return 0
    fi
  fi

  log_step "Requesting certificate for $HYPRCONF_DOMAIN ..."
  cert_arn=$(aws acm request-certificate \
    --domain-name "$HYPRCONF_DOMAIN" \
    --validation-method DNS \
    --region us-east-1 \
    --query 'CertificateArn' --output text)
  state_set CERT_ARN "$cert_arn"
  log_ok "Certificate requested: $cert_arn"

  # ACM takes a few seconds to populate the validation record
  log_step "Waiting for ACM to generate validation record ..."
  local rec_name rec_value
  for i in $(seq 1 12); do
    rec_name=$(aws acm describe-certificate --certificate-arn "$cert_arn" \
      --region us-east-1 \
      --query 'Certificate.DomainValidationOptions[0].ResourceRecord.Name' \
      --output text 2>/dev/null || true)
    [[ -n "$rec_name" && "$rec_name" != "None" ]] && break
    sleep 5
  done
  [[ -n "$rec_name" && "$rec_name" != "None" ]] \
    || log_die "ACM did not provide a validation record after 60s — re-run: hyprconf deploy"

  _upsert_cert_cname "$cert_arn"
  _wait_cert_issued "$cert_arn"
}

# Write (or overwrite) the ACM validation CNAME into Route53 automatically.
_upsert_cert_cname() {
  local cert_arn="$1"
  local rec_name rec_value
  rec_name=$(aws acm describe-certificate --certificate-arn "$cert_arn" \
    --region us-east-1 \
    --query 'Certificate.DomainValidationOptions[0].ResourceRecord.Name' \
    --output text)
  rec_value=$(aws acm describe-certificate --certificate-arn "$cert_arn" \
    --region us-east-1 \
    --query 'Certificate.DomainValidationOptions[0].ResourceRecord.Value' \
    --output text)

  log_step "Adding validation CNAME to Route53 zone $HYPRCONF_ZONE_ID ..."
  printf '%s  %s%s%s\n' "$DM" "$WH" "$rec_name  →  $rec_value" "$RS"

  local change_batch
  change_batch=$(printf '{"Changes":[{"Action":"UPSERT","ResourceRecordSet":{"Name":"%s","Type":"CNAME","TTL":60,"ResourceRecords":[{"Value":"%s"}]}}]}' \
    "$rec_name" "$rec_value")

  aws route53 change-resource-record-sets \
    --hosted-zone-id "$HYPRCONF_ZONE_ID" \
    --change-batch "$change_batch" \
    --output text --query 'ChangeInfo.Status' >/dev/null

  log_ok "Validation CNAME created in Route53."
}

# Poll until ACM marks the certificate ISSUED (typically 1–3 minutes).
_wait_cert_issued() {
  local cert_arn="$1"
  log_step "Waiting for ACM to validate certificate (usually 1–3 min) ..."
  local i status
  for i in $(seq 1 36); do
    status=$(aws acm describe-certificate --certificate-arn "$cert_arn" \
      --region us-east-1 --query 'Certificate.Status' --output text 2>/dev/null || true)
    if [[ "$status" == "ISSUED" ]]; then
      log_ok "Certificate issued: $cert_arn"
      return 0
    fi
    printf '\r%s  [%d/36] Status: %s — waiting ...%s' "$DM" "$i" "$status" "$RS"
    sleep 5
  done
  printf '\n'
  log_die "Certificate not issued after 3 min. Status: $status — re-run: hyprconf deploy"
}

# ── Step 3: CloudFront distribution ──────────────────────────────────────────
deploy_cdn() {
  log_head "CloudFront"

  local cert_arn; cert_arn="$(state_get CERT_ARN)"
  local dist_id; dist_id="$(state_get DISTRIBUTION_ID)"

  if [[ -n "$dist_id" ]]; then
    local dist_domain
    dist_domain=$(aws cloudfront get-distribution --id "$dist_id" \
      --query 'Distribution.DomainName' --output text 2>/dev/null || true)
    if [[ -n "$dist_domain" ]]; then
      log_ok "Distribution exists: $dist_id ($dist_domain)"
      state_set DISTRIBUTION_DOMAIN "$dist_domain"
      # Invalidate /* — covers both the explicit /install.sh path and the
      # distribution root / (DefaultRootObject), which are separate cache entries.
      log_step "Invalidating CloudFront cache (/* — root + install.sh) ..."
      local inv_id
      inv_id=$(aws cloudfront create-invalidation \
        --distribution-id "$dist_id" --paths '/*' \
        --query 'Invalidation.Id' --output text)
      log_info "Invalidation $inv_id in progress — waiting for completion ..."
      aws cloudfront wait invalidation-completed \
        --distribution-id "$dist_id" --id "$inv_id"
      log_ok "Cache cleared — updated install.sh is live at https://${HYPRCONF_DOMAIN}"
      return 0
    fi
  fi

  log_step "Creating CloudFront distribution ..."
  local s3_origin="${HYPRCONF_BUCKET}.s3.${AWS_DEFAULT_REGION:-us-east-1}.amazonaws.com"
  local result
  result=$(aws cloudfront create-distribution --distribution-config "{
    \"CallerReference\": \"hyprconf-$(date +%s)\",
    \"Comment\": \"hyprconf install endpoint — ${HYPRCONF_DOMAIN}\",
    \"Origins\": {
      \"Quantity\": 1,
      \"Items\": [{
        \"Id\": \"s3-origin\",
        \"DomainName\": \"$s3_origin\",
        \"S3OriginConfig\": { \"OriginAccessIdentity\": \"\" }
      }]
    },
    \"DefaultRootObject\": \"install.sh\",
    \"DefaultCacheBehavior\": {
      \"TargetOriginId\": \"s3-origin\",
      \"ViewerProtocolPolicy\": \"redirect-to-https\",
      \"CachePolicyId\": \"658327ea-f89d-4fab-a63d-7e88639e58f6\",
      \"Compress\": true,
      \"AllowedMethods\": {
        \"Quantity\": 2,
        \"Items\": [\"GET\", \"HEAD\"],
        \"CachedMethods\": { \"Quantity\": 2, \"Items\": [\"GET\", \"HEAD\"] }
      }
    },
    \"Aliases\": { \"Quantity\": 1, \"Items\": [\"$HYPRCONF_DOMAIN\"] },
    \"ViewerCertificate\": {
      \"ACMCertificateArn\": \"$cert_arn\",
      \"SSLSupportMethod\": \"sni-only\",
      \"MinimumProtocolVersion\": \"TLSv1.2_2021\"
    },
    \"PriceClass\": \"PriceClass_100\",
    \"Enabled\": true
  }")

  local dist_id dist_domain
  dist_id=$(printf '%s' "$result"     | grep -o '"Id": "[^"]*"' | head -1 | cut -d'"' -f4)
  dist_domain=$(printf '%s' "$result" | grep -o '"DomainName": "[^"]*cloudfront\.net"' | head -1 | cut -d'"' -f4)

  state_set DISTRIBUTION_ID     "$dist_id"
  state_set DISTRIBUTION_DOMAIN "$dist_domain"
  log_ok "Distribution created: $dist_id"
  log_info "CloudFront domain: $dist_domain  (DNS propagation ~15 min)"
}

# ── Step 4: Route53 alias record ──────────────────────────────────────────────
deploy_dns() {
  log_head "Route53"

  local dist_domain; dist_domain="$(state_get DISTRIBUTION_DOMAIN)"
  [[ -n "$dist_domain" ]] \
    || log_die "No CloudFront domain in state — deploy_cdn must run first."

  log_step "Aliasing $HYPRCONF_DOMAIN → $dist_domain ..."
  local existing action="CREATE"
  existing=$(aws route53 list-resource-record-sets \
    --hosted-zone-id "$HYPRCONF_ZONE_ID" \
    --query "ResourceRecordSets[?Name=='${HYPRCONF_DOMAIN}.'].Name" \
    --output text 2>/dev/null || true)
  [[ -n "$existing" ]] && action="UPSERT"

  aws route53 change-resource-record-sets \
    --hosted-zone-id "$HYPRCONF_ZONE_ID" \
    --change-batch "{
      \"Changes\": [{
        \"Action\": \"$action\",
        \"ResourceRecordSet\": {
          \"Name\": \"$HYPRCONF_DOMAIN\",
          \"Type\": \"A\",
          \"AliasTarget\": {
            \"HostedZoneId\": \"Z2FDTNDATAQYW2\",
            \"DNSName\": \"$dist_domain\",
            \"EvaluateTargetHealth\": false
          }
        }
      }]
    }" --output text > /dev/null
  log_ok "DNS record ${action}D."
}

# ── Entry ─────────────────────────────────────────────────────────────────────
main() {
  # shellcheck source=../assets/banner.sh
  source "$ROOT_DIR/assets/banner.sh" 2>/dev/null || true
  print_banner

  configure_env
  deploy_bucket
  deploy_cert
  deploy_cdn
  deploy_dns

  printf '\n%s  ──────────────────────────────────────────────────────────────%s\n' "$GR" "$RS"
  printf '%s  ✔  Deploy complete!%s\n' "$GR" "$RS"
  printf '%s  ──────────────────────────────────────────────────────────────%s\n\n' "$GR" "$RS"
  printf '%s  Install URL:   %shttps://%s%s\n'                       "$DM" "$AM" "$HYPRCONF_DOMAIN" "$RS"
  printf '%s  One-liner:     %sbash <(curl -fsSL https://%s)%s\n'    "$DM" "$WH" "$HYPRCONF_DOMAIN" "$RS"
  printf '%s  Config file:   %s%s%s\n'                                "$DM" "$DM" "$CFG_FILE"        "$RS"
  printf '%s  State file:    %s%s%s\n\n'                              "$DM" "$DM" "$STATE_FILE"       "$RS"
}

main "$@"
