#!/usr/bin/env bash
#
#  infra/deploy.sh — idempotent AWS deploy for hyprconf
#
#  Invoked via:  hyprconf deploy
#  Or directly:  bash infra/deploy.sh
#
#  On first run, prompts interactively for all required settings and saves
#  them to ~/.config/hyprconf/infra.env (outside the repo, chmod 600).
#  Subsequent runs (and 'hyprconf deploy' refreshes) load from that file
#  without prompting, making the command fully idempotent.
#
#  For CI/CD or scripted use, export all required variables before calling
#  this script — it will skip the interactive prompts automatically.
#
#  Required variables (after interactive setup or manual export):
#    HYPRCONF_DOMAIN      — domain to serve install.sh (e.g. get.yourdomain.com)
#    HYPRCONF_BUCKET      — S3 bucket name (globally unique)
#    HYPRCONF_ZONE_ID     — Route53 hosted zone ID for parent domain
#
#  Optional:
#    HYPRCONF_REPO        — GitHub repo URL (auto-detected from git remote)
#    AWS_PROFILE          — named AWS profile
#    AWS_ACCESS_KEY_ID    — explicit credentials (alternative to profile)
#    AWS_SECRET_ACCESS_KEY
#    AWS_DEFAULT_REGION   — defaults to us-east-1 (required for CloudFront ACM)

set -euo pipefail

INFRA_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$INFRA_DIR")"

# Config and state live OUTSIDE the repo so they are never accidentally committed.
# Callers may override paths to support multiple domains:
#   HYPRCONF_INFRA_CFG_FILE=... HYPRCONF_INFRA_STATE_FILE=... bash infra/deploy.sh
DEFAULT_CFG_DIR="$HOME/.config/hyprconf"
CFG_FILE="${HYPRCONF_INFRA_CFG_FILE:-$DEFAULT_CFG_DIR/infra.env}"
STATE_FILE="${HYPRCONF_INFRA_STATE_FILE:-$DEFAULT_CFG_DIR/deploy-state}"
CFG_DIR="$(dirname "$CFG_FILE")"
STATE_DIR="$(dirname "$STATE_FILE")"

# ── Colour palette ────────────────────────────────────────────────────────────
if [[ -t 1 ]]; then
  WH=$'\e[1;37m' GL=$'\e[1;31m' AM=$'\e[1;33m'
  GR=$'\e[1;32m' DM=$'\e[2;37m' RS=$'\e[0m'
else
  WH='' GL='' AM='' GR='' DM='' RS=''
fi

log_step() { printf '%s  ▸ %s%s%s\n'        "$AM" "$WH" "$1" "$RS"; }
log_ok()   { printf '%s  ✔ %s%s%s\n'        "$GR" "$WH" "$1" "$RS"; }
log_warn() { printf '%s  ! %s%s%s\n'        "$AM" "$WH" "$1" "$RS"; }
log_info() { printf '%s  ─ %s%s%s\n'        "$DM" "$WH" "$1" "$RS"; }
log_die()  { printf '%s  ✘ FATAL: %s%s%s\n' "$GL" "$WH" "$1" "$RS" >&2; exit 1; }
log_head() { printf '\n%s  ── %s ─%s\n\n'   "$DM" "$1" "$RS"; }

# ── State helpers ─────────────────────────────────────────────────────────────
state_get() { grep "^${1}=" "$STATE_FILE" 2>/dev/null | cut -d= -f2- || true; }
state_set() {
  mkdir -p "$CFG_DIR" "$STATE_DIR"
  touch "$STATE_FILE"
  if grep -q "^${1}=" "$STATE_FILE" 2>/dev/null; then
    sed -i "s|^${1}=.*|${1}=${2}|" "$STATE_FILE"
  else
    printf '%s=%s\n' "$1" "$2" >> "$STATE_FILE"
  fi
}

# ── Interactive prompt helper ─────────────────────────────────────────────────
# _ask VAR "Label" ["default"]  — reads input, keeps existing/default if blank
_ask() {
  local var="$1" label="$2" default="${3:-}"
  local current="${!var:-}"
  local hint=""
  [[ -n "$current" ]] && hint=" [${current}]" || { [[ -n "$default" ]] && hint=" [${default}]"; }
  printf '%s  %s%s%s: ' "$DM" "$WH" "${label}${hint}" "$RS"
  local input; read -r input
  input="${input:-${current:-$default}}"
  [[ -n "$input" ]] || { printf '%s  Value required.%s\n' "$GL" "$RS"; return 1; }
  printf -v "$var" '%s' "$input"
  export "${var?}"
}

# _ask_secret — like _ask but hides input (for credentials)
_ask_secret() {
  local var="$1" label="$2"
  printf '%s  %s%s (hidden)%s: ' "$DM" "$WH" "$label" "$RS"
  local input; read -rs input; printf '\n'
  [[ -n "$input" ]] || { printf '%s  Value required.%s\n' "$GL" "$RS"; return 1; }
  printf -v "$var" '%s' "$input"
  export "${var?}"
}

# ── Save config file ──────────────────────────────────────────────────────────
_save_config() {
  mkdir -p "$CFG_DIR"
  ( umask 077
    printf '# hyprconf deployment configuration\n'
    printf '# Generated by: hyprconf deploy\n'
    printf '# To reconfigure: delete this file and re-run hyprconf deploy\n'
    printf '# KEEP THIS FILE PRIVATE — it may contain AWS credentials.\n\n'
    [[ -n "${AWS_PROFILE:-}"             ]] && printf 'export AWS_PROFILE="%s"\n'             "$AWS_PROFILE"
    [[ -n "${AWS_ACCESS_KEY_ID:-}"       ]] && printf 'export AWS_ACCESS_KEY_ID="%s"\n'       "$AWS_ACCESS_KEY_ID"
    [[ -n "${AWS_SECRET_ACCESS_KEY:-}"   ]] && printf 'export AWS_SECRET_ACCESS_KEY="%s"\n'   "$AWS_SECRET_ACCESS_KEY"
    [[ -n "${AWS_SESSION_TOKEN:-}"       ]] && printf 'export AWS_SESSION_TOKEN="%s"\n'       "$AWS_SESSION_TOKEN"
    printf 'export AWS_DEFAULT_REGION="%s"\n'  "${AWS_DEFAULT_REGION:-us-east-1}"
    printf '\n'
    printf 'export HYPRCONF_DOMAIN="%s"\n'     "$HYPRCONF_DOMAIN"
    printf 'export HYPRCONF_BUCKET="%s"\n'     "$HYPRCONF_BUCKET"
    printf 'export HYPRCONF_ZONE_ID="%s"\n'    "$HYPRCONF_ZONE_ID"
    printf 'export HYPRCONF_REPO="%s"\n'       "${HYPRCONF_REPO:-}"
  ) > "$CFG_FILE"
  log_ok "Config saved → $CFG_FILE"
}

# ── AWS authentication setup ──────────────────────────────────────────────────
_configure_aws() {
  if aws sts get-caller-identity &>/dev/null 2>&1; then
    log_ok "AWS credentials already valid."
    return 0
  fi

  printf '\n%s  [ AWS Authentication ]%s\n' "$AM" "$RS"
  printf '%s  1) Named profile (recommended — uses ~/.aws/config)\n' "$DM"
  printf '  2) Access key + secret (for accounts without local AWS config)%s\n' "$RS"
  printf '%s  Choice [1]: %s' "$WH" "$RS"
  local choice; read -r choice; choice="${choice:-1}"

  if [[ "$choice" == "2" ]]; then
    _ask        AWS_ACCESS_KEY_ID     "Access Key ID"
    _ask_secret AWS_SECRET_ACCESS_KEY "Secret Access Key"
    printf '%s  Session Token%s (press Enter to skip): ' "$DM$WH" "$DM"
    local tok; read -rs tok; printf '\n'
    [[ -n "$tok" ]] && { AWS_SESSION_TOKEN="$tok"; export AWS_SESSION_TOKEN; }
  else
    _ask AWS_PROFILE "AWS profile name" "default"
  fi

  aws sts get-caller-identity &>/dev/null 2>&1 \
    || log_die "AWS authentication failed. Check your credentials and try again."
  log_ok "AWS credentials valid."
}

# ── Route53 zone selection ────────────────────────────────────────────────────
_select_zone() {
  log_step "Fetching Route53 hosted zones..."

  local zones_raw
  zones_raw=$(aws route53 list-hosted-zones \
    --query 'HostedZones[].[Name,Id]' --output text 2>/dev/null) || {
    log_warn "Could not list hosted zones. Enter your Zone ID manually."
    _ask HYPRCONF_ZONE_ID "Route53 Hosted Zone ID"
    return
  }

  if [[ -z "$zones_raw" ]]; then
    log_warn "No hosted zones found in this AWS account."
    _ask HYPRCONF_ZONE_ID "Route53 Hosted Zone ID"
    return
  fi

  local names=() ids=()
  while IFS=$'\t' read -r name id; do
    names+=("${name%.}")               # strip trailing dot
    ids+=("${id##*/hostedzone/}")      # extract ID from /hostedzone/XXXX
  done <<< "$zones_raw"

  # Try to auto-match: find any zone whose name the domain ends with
  local match_idx=-1
  for i in "${!names[@]}"; do
    if [[ "$HYPRCONF_DOMAIN" == *.${names[$i]} ]] || \
       [[ "$HYPRCONF_DOMAIN" == "${names[$i]}" ]]; then
      match_idx=$i
    fi
  done

  if [[ $match_idx -ge 0 ]]; then
    printf '%s  Auto-matched zone: %s%s%s  (%s)\n' \
      "$GR" "$WH" "${names[$match_idx]}" "$RS" "${ids[$match_idx]}"
    printf '%s  Use this zone? [Y/n]: %s' "$DM$WH" "$RS"
    local yn; read -r yn
    if [[ "${yn,,}" != "n" ]]; then
      HYPRCONF_ZONE_ID="${ids[$match_idx]}"; export HYPRCONF_ZONE_ID
      return
    fi
  fi

  # Show menu
  printf '\n%s  Available hosted zones:%s\n' "$AM" "$RS"
  for i in "${!names[@]}"; do
    printf '%s  %2d)  %-35s %s%s\n' "$DM" $((i+1)) "${names[$i]}" "${ids[$i]}" "$RS"
  done
  printf '%s  Select zone number: %s' "$WH" "$RS"
  local sel; read -r sel
  local idx=$(( sel - 1 ))
  [[ $idx -ge 0 && $idx -lt ${#ids[@]} ]] \
    || log_die "Invalid selection."
  HYPRCONF_ZONE_ID="${ids[$idx]}"; export HYPRCONF_ZONE_ID
}

# ── Auto-detect existing infrastructure ───────────────────────────────────────
# Searches AWS for existing CloudFront / ACM / S3 resources tied to
# HYPRCONF_DOMAIN and pre-populates the state file so every deploy step is
# idempotent — critical when a dev uses a new device without a local state file.
_autodetect_infra() {
  local dist_id; dist_id="$(state_get DISTRIBUTION_ID)"
  local cert_arn; cert_arn="$(state_get CERT_ARN)"
  [[ -n "$dist_id" && -n "$cert_arn" ]] && return 0

  log_step "Auto-detecting existing infrastructure for ${HYPRCONF_DOMAIN} ..."

  # ── CloudFront: find distribution by CNAME alias ──────────────────────────
  if [[ -z "$dist_id" ]]; then
    dist_id=$(aws cloudfront list-distributions \
      --query "DistributionList.Items[?Aliases.Items[?@=='${HYPRCONF_DOMAIN}']].Id | [0]" \
      --output text 2>/dev/null || true)
    [[ "$dist_id" == "None" || "$dist_id" == "null" ]] && dist_id=""

    if [[ -n "$dist_id" ]]; then
      local dist_domain
      dist_domain=$(aws cloudfront get-distribution --id "$dist_id" \
        --query 'Distribution.DomainName' --output text 2>/dev/null || true)
      state_set DISTRIBUTION_ID     "$dist_id"
      state_set DISTRIBUTION_DOMAIN "$dist_domain"
      log_ok "Detected CloudFront distribution: $dist_id  ($dist_domain)"

      # Extract ACM cert ARN from the distribution's viewer certificate config
      if [[ -z "$cert_arn" ]]; then
        cert_arn=$(aws cloudfront get-distribution --id "$dist_id" \
          --query 'Distribution.DistributionConfig.ViewerCertificate.ACMCertificateArn' \
          --output text 2>/dev/null || true)
        [[ "$cert_arn" == "None" || "$cert_arn" == "null" ]] && cert_arn=""
        if [[ -n "$cert_arn" ]]; then
          state_set CERT_ARN "$cert_arn"
          log_ok "Detected ACM certificate: $cert_arn"
        fi
      fi

      # Extract S3 bucket from origin domain (bucket.s3.region.amazonaws.com)
      if [[ -z "${HYPRCONF_BUCKET:-}" ]]; then
        local origin_domain detected_bucket
        origin_domain=$(aws cloudfront get-distribution --id "$dist_id" \
          --query 'Distribution.DistributionConfig.Origins.Items[0].DomainName' \
          --output text 2>/dev/null || true)
        detected_bucket=$(printf '%s' "$origin_domain" | sed 's/\.s3\..*//')
        if [[ -n "$detected_bucket" && "$detected_bucket" != "$origin_domain" ]]; then
          HYPRCONF_BUCKET="$detected_bucket"; export HYPRCONF_BUCKET
          log_ok "Detected S3 bucket: $HYPRCONF_BUCKET"
        fi
      fi
    fi
  fi

  # ── ACM: direct lookup if cert still not found via CloudFront ─────────────
  if [[ -z "$cert_arn" ]]; then
    cert_arn=$(aws acm list-certificates --region us-east-1 \
      --query "CertificateSummaryList[?DomainName=='${HYPRCONF_DOMAIN}' && Status=='ISSUED'].CertificateArn | [0]" \
      --output text 2>/dev/null || true)
    [[ "$cert_arn" == "None" || "$cert_arn" == "null" ]] && cert_arn=""
    if [[ -n "$cert_arn" ]]; then
      state_set CERT_ARN "$cert_arn"
      log_ok "Detected ACM certificate: $cert_arn"
    fi
  fi
}

# ── Interactive environment configuration ─────────────────────────────────────
configure_env() {
  # Load saved config if present (vars already in env take priority)
  [[ -f "$CFG_FILE" ]] && source "$CFG_FILE"

  # If everything is already configured, skip all prompts
  if [[ -n "${HYPRCONF_DOMAIN:-}"   ]] && \
     [[ -n "${HYPRCONF_BUCKET:-}"   ]] && \
     [[ -n "${HYPRCONF_ZONE_ID:-}"  ]] && \
     aws sts get-caller-identity &>/dev/null 2>&1; then
    log_ok "Config loaded from $CFG_FILE"
    return 0
  fi

  [[ -t 0 ]] \
    || log_die "Configuration incomplete and no interactive terminal available.
       Export required variables or run 'hyprconf deploy' interactively."

  log_head "hyprconf deploy — first-time setup"
  printf '%s  Settings will be saved to: %s%s%s\n\n' \
    "$DM" "$WH" "$CFG_FILE" "$RS"

  command -v aws &>/dev/null \
    || log_die "AWS CLI not found. Install: https://aws.amazon.com/cli/"

  # AWS credentials
  _configure_aws

  # Region
  printf '\n%s  [ Region ]%s\n' "$AM" "$RS"
  printf '%s  Must be us-east-1 for CloudFront ACM certificates.%s\n' "$DM" "$RS"
  _ask AWS_DEFAULT_REGION "AWS region" "us-east-1"

  # Domain
  printf '\n%s  [ Install Domain ]%s\n' "$AM" "$RS"
  printf '%s  The domain where your install.sh will be served over HTTPS.\n' "$DM"
  printf '  Example: get.yourdomain.com%s\n' "$RS"
  while [[ -z "${HYPRCONF_DOMAIN:-}" ]]; do
    _ask HYPRCONF_DOMAIN "Domain"
  done

  # S3 bucket (suggest from domain)
  printf '\n%s  [ S3 Bucket ]%s\n' "$AM" "$RS"
  local suggested_bucket; suggested_bucket=$(printf '%s' "$HYPRCONF_DOMAIN" | tr '.' '-')
  _ask HYPRCONF_BUCKET "S3 bucket name (must be globally unique)" "$suggested_bucket"

  # Route53 zone
  printf '\n%s  [ Route53 Hosted Zone ]%s\n' "$AM" "$RS"
  if [[ -z "${HYPRCONF_ZONE_ID:-}" ]]; then
    _select_zone
  else
    log_ok "Zone ID already set: $HYPRCONF_ZONE_ID"
  fi

  # GitHub repo
  printf '\n%s  [ Repository URL ]%s\n' "$AM" "$RS"
  printf '%s  The repo cloned by your install.sh bootstrap.%s\n' "$DM" "$RS"
  local detected_repo
  detected_repo=$(git -C "$ROOT_DIR" remote get-url origin 2>/dev/null \
    | sed 's|^git@github\.com:|https://github.com/|; s|\.git$||' || true)
  _ask HYPRCONF_REPO "GitHub repo URL" "$detected_repo"

  printf '\n'
  _save_config
}

# ── Step 1: S3 bucket + install.sh upload ─────────────────────────────────────
deploy_bucket() {
  log_head "S3"

  if ! aws s3api head-bucket --bucket "$HYPRCONF_BUCKET" 2>/dev/null; then
    log_step "Creating bucket $HYPRCONF_BUCKET ..."
    local args=(--bucket "$HYPRCONF_BUCKET")
    [[ "${AWS_DEFAULT_REGION:-us-east-1}" != "us-east-1" ]] && \
      args+=(--create-bucket-configuration "LocationConstraint=${AWS_DEFAULT_REGION}")
    aws s3api create-bucket "${args[@]}" --output text > /dev/null
    log_ok "Bucket created."
  else
    log_ok "Bucket exists."
  fi

  _ensure_bucket_policy

  # Inject this fork's repo URL into install.sh before uploading.
  # The source file keeps the original URL; the deployed copy uses HYPRCONF_REPO.
  log_step "Uploading install.sh (repo: ${HYPRCONF_REPO}) ..."
  local tmp; tmp=$(mktemp)
  sed "s|^readonly REPO_URL=.*|readonly REPO_URL=\"${HYPRCONF_REPO}\"|" \
    "$ROOT_DIR/install/install.sh" > "$tmp"
  aws s3 cp "$tmp" "s3://$HYPRCONF_BUCKET/install.sh" \
    --content-type 'text/plain; charset=utf-8' \
    --cache-control 'no-cache, no-store' > /dev/null
  rm -f "$tmp"
  log_ok "install.sh uploaded → s3://$HYPRCONF_BUCKET/install.sh"
}

# ── Ensure bucket policy allows public read on all objects ────────────────────
# Idempotent — safe to call from any code path (full deploy, web-only, etc.).
_ensure_bucket_policy() {
  log_step "Ensuring bucket policy allows public read on all objects ..."

  # Disable Block Public Access (both bucket-level settings)
  aws s3api put-public-access-block --bucket "$HYPRCONF_BUCKET" \
    --public-access-block-configuration \
    'BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false'

  local policy="{
    \"Version\": \"2012-10-17\",
    \"Statement\": [{
      \"Sid\": \"PublicReadAllObjects\",
      \"Effect\": \"Allow\",
      \"Principal\": \"*\",
      \"Action\": \"s3:GetObject\",
      \"Resource\": \"arn:aws:s3:::${HYPRCONF_BUCKET}/*\"
    }]
  }"
  aws s3api put-bucket-policy --bucket "$HYPRCONF_BUCKET" --policy "$policy"

  # Verify the policy was applied
  local applied_resource
  applied_resource=$(aws s3api get-bucket-policy --bucket "$HYPRCONF_BUCKET" \
    --query 'Policy' --output text 2>/dev/null \
    | python3 -c "import sys,json; p=json.load(sys.stdin); print(p['Statement'][0]['Resource'])" 2>/dev/null || echo "")
  if [[ "$applied_resource" == *"/*" ]]; then
    log_ok "Bucket policy verified — public read on all objects."
  else
    log_warn "Bucket policy verification failed — site may return AccessDenied."
    log_warn "Check account-level S3 Block Public Access settings in the AWS Console."
  fi
}

# ── Step 1b: Build + upload web frontend ──────────────────────────────────────
deploy_web() {
  log_head "Web Frontend"

  local web_dir="$ROOT_DIR/web"
  local dist_dir="$web_dir/dist"

  if [[ ! -d "$web_dir" ]] || [[ ! -f "$web_dir/package.json" ]]; then
    log_warn "web/ directory not found — skipping frontend deploy."
    return 0
  fi

  # Check node/npm availability
  if ! command -v npm &>/dev/null; then
    log_warn "npm not found — skipping frontend build. Install Node.js to deploy the web UI."
    return 0
  fi

  log_step "Installing web dependencies ..."
  (cd "$web_dir" && npm install --silent)

  log_step "Building web frontend ..."
  (cd "$web_dir" && npm run build)

  if [[ ! -d "$dist_dir" ]] || [[ ! -f "$dist_dir/index.html" ]]; then
    log_warn "Build produced no output — skipping frontend upload."
    return 0
  fi

  log_step "Syncing web assets to s3://$HYPRCONF_BUCKET/ ..."
  aws s3 sync "$dist_dir" "s3://$HYPRCONF_BUCKET/" \
    --exclude "install.sh" \
    --delete \
    --cache-control 'public, max-age=31536000, immutable' \
    > /dev/null

  # index.html should never be cached aggressively (SPA entry point)
  aws s3 cp "$dist_dir/index.html" "s3://$HYPRCONF_BUCKET/index.html" \
    --content-type 'text/html; charset=utf-8' \
    --cache-control 'no-cache, no-store' \
    > /dev/null

  log_ok "Web frontend deployed to s3://$HYPRCONF_BUCKET/"
}

# ── Step 2: ACM certificate (us-east-1 only) ──────────────────────────────────
deploy_cert() {
  log_head "ACM Certificate"

  local cert_arn; cert_arn="$(state_get CERT_ARN)"

  if [[ -n "$cert_arn" ]]; then
    local status
    status=$(aws acm describe-certificate --certificate-arn "$cert_arn" \
      --region us-east-1 --query 'Certificate.Status' --output text 2>/dev/null || true)
    if [[ "$status" == "ISSUED" ]]; then
      log_ok "Certificate already issued: $cert_arn"; return 0
    elif [[ "$status" == "PENDING_VALIDATION" ]]; then
      log_step "Certificate pending — attempting to auto-validate via Route53 ..."
      _upsert_cert_cname "$cert_arn"
      _wait_cert_issued "$cert_arn"
      return 0
    fi
  fi

  log_step "Requesting certificate for $HYPRCONF_DOMAIN ..."
  cert_arn=$(aws acm request-certificate \
    --domain-name "$HYPRCONF_DOMAIN" \
    --validation-method DNS \
    --region us-east-1 \
    --query 'CertificateArn' --output text)
  state_set CERT_ARN "$cert_arn"
  log_ok "Certificate requested: $cert_arn"

  # ACM takes a few seconds to populate the validation record
  log_step "Waiting for ACM to generate validation record ..."
  local rec_name rec_value
  for i in $(seq 1 12); do
    rec_name=$(aws acm describe-certificate --certificate-arn "$cert_arn" \
      --region us-east-1 \
      --query 'Certificate.DomainValidationOptions[0].ResourceRecord.Name' \
      --output text 2>/dev/null || true)
    [[ -n "$rec_name" && "$rec_name" != "None" ]] && break
    sleep 5
  done
  [[ -n "$rec_name" && "$rec_name" != "None" ]] \
    || log_die "ACM did not provide a validation record after 60s — re-run: hyprconf deploy"

  _upsert_cert_cname "$cert_arn"
  _wait_cert_issued "$cert_arn"
}

# Write (or overwrite) the ACM validation CNAME into Route53 automatically.
_upsert_cert_cname() {
  local cert_arn="$1"
  local rec_name rec_value
  rec_name=$(aws acm describe-certificate --certificate-arn "$cert_arn" \
    --region us-east-1 \
    --query 'Certificate.DomainValidationOptions[0].ResourceRecord.Name' \
    --output text)
  rec_value=$(aws acm describe-certificate --certificate-arn "$cert_arn" \
    --region us-east-1 \
    --query 'Certificate.DomainValidationOptions[0].ResourceRecord.Value' \
    --output text)

  log_step "Adding validation CNAME to Route53 zone $HYPRCONF_ZONE_ID ..."
  printf '%s  %s%s%s\n' "$DM" "$WH" "$rec_name  →  $rec_value" "$RS"

  local change_batch
  change_batch=$(printf '{"Changes":[{"Action":"UPSERT","ResourceRecordSet":{"Name":"%s","Type":"CNAME","TTL":60,"ResourceRecords":[{"Value":"%s"}]}}]}' \
    "$rec_name" "$rec_value")

  aws route53 change-resource-record-sets \
    --hosted-zone-id "$HYPRCONF_ZONE_ID" \
    --change-batch "$change_batch" \
    --output text --query 'ChangeInfo.Status' >/dev/null

  log_ok "Validation CNAME created in Route53."
}

# Poll until ACM marks the certificate ISSUED (typically 1–3 minutes).
_wait_cert_issued() {
  local cert_arn="$1"
  log_step "Waiting for ACM to validate certificate (usually 1–3 min) ..."
  local i status
  for i in $(seq 1 36); do
    status=$(aws acm describe-certificate --certificate-arn "$cert_arn" \
      --region us-east-1 --query 'Certificate.Status' --output text 2>/dev/null || true)
    if [[ "$status" == "ISSUED" ]]; then
      log_ok "Certificate issued: $cert_arn"
      return 0
    fi
    printf '\r%s  [%d/36] Status: %s — waiting ...%s' "$DM" "$i" "$status" "$RS"
    sleep 5
  done
  printf '\n'
  log_die "Certificate not issued after 3 min. Status: $status — re-run: hyprconf deploy"
}

# ── Step 3: CloudFront distribution ──────────────────────────────────────────
deploy_cdn() {
  log_head "CloudFront"

  local cert_arn; cert_arn="$(state_get CERT_ARN)"
  local dist_id; dist_id="$(state_get DISTRIBUTION_ID)"

  if [[ -n "$dist_id" ]]; then
    local dist_domain
    dist_domain=$(aws cloudfront get-distribution --id "$dist_id" \
      --query 'Distribution.DomainName' --output text 2>/dev/null || true)
    if [[ -n "$dist_domain" ]]; then
      log_ok "Distribution exists: $dist_id ($dist_domain)"
      state_set DISTRIBUTION_DOMAIN "$dist_domain"
      _deploy_cf_function "$dist_id"
      _invalidate_cdn "$dist_id"
      return 0
    fi
  fi

  # Belt-and-suspenders: search by CNAME in case _autodetect_infra missed it
  # (e.g. deploy_cdn called directly without going through main).
  dist_id=$(aws cloudfront list-distributions \
    --query "DistributionList.Items[?Aliases.Items[?@=='${HYPRCONF_DOMAIN}']].Id | [0]" \
    --output text 2>/dev/null || true)
  [[ "$dist_id" == "None" || "$dist_id" == "null" ]] && dist_id=""
  if [[ -n "$dist_id" ]]; then
    local dist_domain_found
    dist_domain_found=$(aws cloudfront get-distribution --id "$dist_id" \
      --query 'Distribution.DomainName' --output text 2>/dev/null || true)
    state_set DISTRIBUTION_ID     "$dist_id"
    state_set DISTRIBUTION_DOMAIN "$dist_domain_found"
    log_ok "Detected existing distribution for ${HYPRCONF_DOMAIN}: $dist_id"
    _deploy_cf_function "$dist_id"
    _invalidate_cdn "$dist_id"
    return 0
  fi

  log_step "Creating CloudFront distribution ..."
  local s3_origin="${HYPRCONF_BUCKET}.s3.${AWS_DEFAULT_REGION:-us-east-1}.amazonaws.com"
  local result
  result=$(aws cloudfront create-distribution --distribution-config "{
    \"CallerReference\": \"hyprconf-$(date +%s)\",
    \"Comment\": \"hyprconf install + web — ${HYPRCONF_DOMAIN}\",
    \"Origins\": {
      \"Quantity\": 1,
      \"Items\": [{
        \"Id\": \"s3-origin\",
        \"DomainName\": \"$s3_origin\",
        \"S3OriginConfig\": { \"OriginAccessIdentity\": \"\" }
      }]
    },
    \"DefaultRootObject\": \"index.html\",
    \"DefaultCacheBehavior\": {
      \"TargetOriginId\": \"s3-origin\",
      \"ViewerProtocolPolicy\": \"redirect-to-https\",
      \"CachePolicyId\": \"658327ea-f89d-4fab-a63d-7e88639e58f6\",
      \"Compress\": true,
      \"AllowedMethods\": {
        \"Quantity\": 2,
        \"Items\": [\"GET\", \"HEAD\"],
        \"CachedMethods\": { \"Quantity\": 2, \"Items\": [\"GET\", \"HEAD\"] }
      }
    },
    \"Aliases\": { \"Quantity\": 1, \"Items\": [\"$HYPRCONF_DOMAIN\"] },
    \"ViewerCertificate\": {
      \"ACMCertificateArn\": \"$cert_arn\",
      \"SSLSupportMethod\": \"sni-only\",
      \"MinimumProtocolVersion\": \"TLSv1.2_2021\"
    },
    \"PriceClass\": \"PriceClass_100\",
    \"Enabled\": true
  }")

  local dist_id dist_domain
  dist_id=$(printf '%s' "$result"     | grep -o '"Id": "[^"]*"' | head -1 | cut -d'"' -f4)
  dist_domain=$(printf '%s' "$result" | grep -o '"DomainName": "[^"]*cloudfront\.net"' | head -1 | cut -d'"' -f4)

  state_set DISTRIBUTION_ID     "$dist_id"
  state_set DISTRIBUTION_DOMAIN "$dist_domain"
  log_ok "Distribution created: $dist_id"
  log_info "CloudFront domain: $dist_domain  (DNS propagation ~15 min)"

  _deploy_cf_function "$dist_id"
}

# ── CloudFront Function: UA-based routing (curl→install.sh, browser→SPA) ─────
_deploy_cf_function() {
  local dist_id="$1"
  local cf_fn_name="hyprconf-ua-router"
  local cf_fn_file="$INFRA_DIR/cloudfront-function.js"

  if [[ ! -f "$cf_fn_file" ]]; then
    log_warn "CloudFront function source not found ($cf_fn_file) — skipping."
    return 0
  fi

  log_step "Deploying CloudFront Function ($cf_fn_name) ..."

  # describe-function defaults to DEVELOPMENT stage
  local etag
  etag=$(aws cloudfront describe-function \
    --name "$cf_fn_name" --stage DEVELOPMENT \
    --query 'ETag' --output text 2>/dev/null || echo "")

  if [[ -z "$etag" ]] || [[ "$etag" == "None" ]]; then
    log_info "Creating new CloudFront Function ..."
    aws cloudfront create-function \
      --name "$cf_fn_name" \
      --function-config "Comment=UA routing for ${HYPRCONF_DOMAIN},Runtime=cloudfront-js-2.0" \
      --function-code "fileb://$cf_fn_file" \
      > /dev/null \
      || { log_warn "Could not create CloudFront Function — manual setup may be needed."; return 0; }
  else
    log_info "Updating existing function (ETag: $etag) ..."
    aws cloudfront update-function \
      --name "$cf_fn_name" \
      --if-match "$etag" \
      --function-config "Comment=UA routing for ${HYPRCONF_DOMAIN},Runtime=cloudfront-js-2.0" \
      --function-code "fileb://$cf_fn_file" \
      > /dev/null \
      || { log_warn "Could not update CloudFront Function."; return 0; }
  fi

  # Publish the function (DEVELOPMENT → LIVE)
  local dev_etag
  dev_etag=$(aws cloudfront describe-function \
    --name "$cf_fn_name" --stage DEVELOPMENT \
    --query 'ETag' --output text 2>/dev/null || echo "")

  if [[ -n "$dev_etag" ]] && [[ "$dev_etag" != "None" ]]; then
    aws cloudfront publish-function \
      --name "$cf_fn_name" \
      --if-match "$dev_etag" \
      > /dev/null \
      || { log_warn "Could not publish CloudFront Function."; return 0; }
    log_ok "CloudFront Function published."
  fi

  # Ensure function is associated with the distribution's default cache behavior.
  # Without this, browsers would NOT be routed to index.html and the site returns
  # AccessDenied (S3 returns 403 for non-existent paths without ListBucket).
  _ensure_cf_function_association "$dist_id" "$cf_fn_name"
}

# ── Ensure CF function is associated with a distribution ──────────────────────
_ensure_cf_function_association() {
  local dist_id="$1" fn_name="$2"

  # Check if already associated
  local current_fn
  current_fn=$(aws cloudfront get-distribution-config --id "$dist_id" \
    --query 'DistributionConfig.DefaultCacheBehavior.FunctionAssociations.Items[?EventType==`viewer-request`].FunctionARN | [0]' \
    --output text 2>/dev/null || echo "")

  if [[ -n "$current_fn" ]] && [[ "$current_fn" != "None" ]]; then
    log_ok "CF function already associated with distribution."
    return 0
  fi

  log_step "Associating CF function with distribution $dist_id ..."

  # Get the function ARN from the LIVE stage
  local fn_arn
  fn_arn=$(aws cloudfront describe-function \
    --name "$fn_name" --stage LIVE \
    --query 'FunctionSummary.FunctionMetadata.FunctionARN' \
    --output text 2>/dev/null || echo "")

  if [[ -z "$fn_arn" ]] || [[ "$fn_arn" == "None" ]]; then
    log_warn "Could not get function ARN — associate '$fn_name' with the distribution manually."
    return 0
  fi

  # Get the full distribution config + ETag (required for update)
  local tmp_cfg; tmp_cfg=$(mktemp)
  local dist_etag
  dist_etag=$(aws cloudfront get-distribution-config --id "$dist_id" \
    --output json > "$tmp_cfg" && \
    python3 -c "import json,sys; d=json.load(sys.stdin); print(d['ETag'])" < "$tmp_cfg")

  # Inject FunctionAssociations into DefaultCacheBehavior and ensure
  # DefaultRootObject is index.html (fallback if function ever fails).
  local tmp_updated; tmp_updated=$(mktemp)
  python3 -c "
import json, sys

data = json.load(sys.stdin)
cfg = data['DistributionConfig']
cfg['DefaultRootObject'] = 'index.html'
dcb = cfg['DefaultCacheBehavior']
dcb['FunctionAssociations'] = {
    'Quantity': 1,
    'Items': [{
        'FunctionARN': '${fn_arn}',
        'EventType': 'viewer-request'
    }]
}
json.dump(cfg, sys.stdout)
" < "$tmp_cfg" > "$tmp_updated"

  aws cloudfront update-distribution \
    --id "$dist_id" \
    --if-match "$dist_etag" \
    --distribution-config "file://$tmp_updated" \
    > /dev/null 2>&1 \
    && log_ok "CF function associated with distribution." \
    || log_warn "Could not update distribution config — associate '$fn_name' manually."

  rm -f "$tmp_cfg" "$tmp_updated"
}

# ── Cache invalidation helper ─────────────────────────────────────────────────
_invalidate_cdn() {
  local dist_id="$1"
  log_step "Invalidating CloudFront cache ..."
  local inv_id
  inv_id=$(aws cloudfront create-invalidation \
    --distribution-id "$dist_id" --paths '/*' \
    --query 'Invalidation.Id' --output text)
  log_info "Invalidation $inv_id in progress — waiting for completion ..."
  aws cloudfront wait invalidation-completed \
    --distribution-id "$dist_id" --id "$inv_id"
  log_ok "Cache cleared — site live at https://${HYPRCONF_DOMAIN}"
}

# ── Step 4: Route53 alias record ──────────────────────────────────────────────
deploy_dns() {
  log_head "Route53"

  local dist_domain; dist_domain="$(state_get DISTRIBUTION_DOMAIN)"
  [[ -n "$dist_domain" ]] \
    || log_die "No CloudFront domain in state — deploy_cdn must run first."

  log_step "Aliasing $HYPRCONF_DOMAIN → $dist_domain ..."
  local existing action="CREATE"
  existing=$(aws route53 list-resource-record-sets \
    --hosted-zone-id "$HYPRCONF_ZONE_ID" \
    --query "ResourceRecordSets[?Name=='${HYPRCONF_DOMAIN}.'].Name" \
    --output text 2>/dev/null || true)
  [[ -n "$existing" ]] && action="UPSERT"

  aws route53 change-resource-record-sets \
    --hosted-zone-id "$HYPRCONF_ZONE_ID" \
    --change-batch "{
      \"Changes\": [{
        \"Action\": \"$action\",
        \"ResourceRecordSet\": {
          \"Name\": \"$HYPRCONF_DOMAIN\",
          \"Type\": \"A\",
          \"AliasTarget\": {
            \"HostedZoneId\": \"Z2FDTNDATAQYW2\",
            \"DNSName\": \"$dist_domain\",
            \"EvaluateTargetHealth\": false
          }
        }
      }]
    }" --output text > /dev/null
  log_ok "DNS record ${action}D."
}

# ── Entry ─────────────────────────────────────────────────────────────────────
main() {
  # shellcheck source=../assets/banner.sh
  source "$ROOT_DIR/assets/banner.sh" 2>/dev/null || true
  print_banner

  local web_only=false
  if [[ "${1:-}" == "web" ]]; then
    web_only=true
  fi

  configure_env
  _autodetect_infra

  if $web_only; then
    # Quick web-only deploy: build + sync + invalidate. Skips infra setup.
    local dist_id; dist_id="$(state_get DISTRIBUTION_ID)"
    [[ -z "$dist_id" ]] && log_die "No existing deployment found. Run a full deploy first."
    _ensure_bucket_policy
    deploy_web
    _deploy_cf_function "$dist_id"
    _invalidate_cdn "$dist_id"
  else
    deploy_bucket
    deploy_web
    deploy_cert
    deploy_cdn
    deploy_dns
  fi

  printf '\n%s  ──────────────────────────────────────────────────────────────%s\n' "$GR" "$RS"
  printf '%s  ✔  Deploy complete!%s\n' "$GR" "$RS"
  printf '%s  ──────────────────────────────────────────────────────────────%s\n\n' "$GR" "$RS"
  printf '%s  Install URL:   %shttps://%s%s\n'                       "$DM" "$AM" "$HYPRCONF_DOMAIN" "$RS"
  printf '%s  Web frontend:  %shttps://%s%s\n'                       "$DM" "$AM" "$HYPRCONF_DOMAIN" "$RS"
  printf '%s  One-liner:     %sbash <(curl -fsSL https://%s)%s\n'    "$DM" "$WH" "$HYPRCONF_DOMAIN" "$RS"
  printf '%s  Config file:   %s%s%s\n'                                "$DM" "$DM" "$CFG_FILE"        "$RS"
  printf '%s  State file:    %s%s%s\n\n'                              "$DM" "$DM" "$STATE_FILE"       "$RS"
}

main "$@"
