#!/usr/bin/env bash
#
#  infra/deploy.sh — idempotent AWS deploy for hyprconf (CDK-managed)
#
#  Invoked via:  hyprconf deploy
#  Or directly:  bash infra/deploy.sh
#
#  On first run, prompts interactively for all required settings and saves
#  them to ~/.config/hyprconf/infra.env (outside the repo, chmod 600).
#  Subsequent runs (and 'hyprconf deploy' refreshes) load from that file
#  without prompting, making the command fully idempotent.
#
#  All AWS resources are managed by CDK (infra/cdk/). This script is a
#  wrapper that handles: interactive config, web build, install.sh repo
#  injection, then delegates to `cdk deploy`.
#
#  For CI/CD or scripted use, export all required variables before calling
#  this script — it will skip the interactive prompts automatically.
#
#  Required variables (after interactive setup or manual export):
#    HYPRCONF_DOMAIN      — domain to serve install.sh (e.g. get.yourdomain.com)
#    HYPRCONF_BUCKET      — S3 bucket name (globally unique)
#    HYPRCONF_ZONE_ID     — Route53 hosted zone ID for parent domain
#
#  Optional:
#    HYPRCONF_REPO        — GitHub repo URL (auto-detected from git remote)
#    AWS_PROFILE          — named AWS profile
#    AWS_ACCESS_KEY_ID    — explicit credentials (alternative to profile)
#    AWS_SECRET_ACCESS_KEY
#    AWS_DEFAULT_REGION   — defaults to us-east-1 (required for CloudFront ACM)

set -euo pipefail

INFRA_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$INFRA_DIR")"

# Config and state live OUTSIDE the repo so they are never accidentally committed.
# Callers may override paths to support multiple domains:
#   HYPRCONF_INFRA_CFG_FILE=... HYPRCONF_INFRA_STATE_FILE=... bash infra/deploy.sh
DEFAULT_CFG_DIR="$HOME/.config/hyprconf"
CFG_FILE="${HYPRCONF_INFRA_CFG_FILE:-$DEFAULT_CFG_DIR/infra.env}"
STATE_FILE="${HYPRCONF_INFRA_STATE_FILE:-$DEFAULT_CFG_DIR/deploy-state}"
CFG_DIR="$(dirname "$CFG_FILE")"
STATE_DIR="$(dirname "$STATE_FILE")"

# ── Colour palette ────────────────────────────────────────────────────────────
if [[ -t 1 ]]; then
  WH=$'\e[1;37m' GL=$'\e[1;31m' AM=$'\e[1;33m'
  GR=$'\e[1;32m' DM=$'\e[2;37m' RS=$'\e[0m'
else
  WH='' GL='' AM='' GR='' DM='' RS=''
fi

log_step() { printf '%s  ▸ %s%s%s\n'        "$AM" "$WH" "$1" "$RS"; }
log_ok()   { printf '%s  ✔ %s%s%s\n'        "$GR" "$WH" "$1" "$RS"; }
log_warn() { printf '%s  ! %s%s%s\n'        "$AM" "$WH" "$1" "$RS"; }
log_info() { printf '%s  ─ %s%s%s\n'        "$DM" "$WH" "$1" "$RS"; }
log_die()  { printf '%s  ✘ FATAL: %s%s%s\n' "$GL" "$WH" "$1" "$RS" >&2; exit 1; }
log_head() { printf '\n%s  ── %s ─%s\n\n'   "$DM" "$1" "$RS"; }

# ── State helpers ─────────────────────────────────────────────────────────────
state_get() { grep "^${1}=" "$STATE_FILE" 2>/dev/null | cut -d= -f2- || true; }
state_set() {
  mkdir -p "$CFG_DIR" "$STATE_DIR"
  touch "$STATE_FILE"
  if grep -q "^${1}=" "$STATE_FILE" 2>/dev/null; then
    sed -i "s|^${1}=.*|${1}=${2}|" "$STATE_FILE"
  else
    printf '%s=%s\n' "$1" "$2" >> "$STATE_FILE"
  fi
}

# ── Interactive prompt helper ─────────────────────────────────────────────────
# _ask VAR "Label" ["default"]  — reads input, keeps existing/default if blank
_ask() {
  local var="$1" label="$2" default="${3:-}"
  local current="${!var:-}"
  local hint=""
  [[ -n "$current" ]] && hint=" [${current}]" || { [[ -n "$default" ]] && hint=" [${default}]"; }
  printf '%s  %s%s%s: ' "$DM" "$WH" "${label}${hint}" "$RS"
  local input; read -r input
  input="${input:-${current:-$default}}"
  [[ -n "$input" ]] || { printf '%s  Value required.%s\n' "$GL" "$RS"; return 1; }
  printf -v "$var" '%s' "$input"
  export "${var?}"
}

# _ask_secret — like _ask but hides input (for credentials)
_ask_secret() {
  local var="$1" label="$2"
  printf '%s  %s%s (hidden)%s: ' "$DM" "$WH" "$label" "$RS"
  local input; read -rs input; printf '\n'
  [[ -n "$input" ]] || { printf '%s  Value required.%s\n' "$GL" "$RS"; return 1; }
  printf -v "$var" '%s' "$input"
  export "${var?}"
}

# ── Save config file ──────────────────────────────────────────────────────────
_save_config() {
  mkdir -p "$CFG_DIR"
  ( umask 077
    printf '# hyprconf deployment configuration\n'
    printf '# Generated by: hyprconf deploy\n'
    printf '# To reconfigure: delete this file and re-run hyprconf deploy\n'
    printf '# KEEP THIS FILE PRIVATE — it may contain AWS credentials.\n\n'
    [[ -n "${AWS_PROFILE:-}"             ]] && printf 'export AWS_PROFILE="%s"\n'             "$AWS_PROFILE"
    [[ -n "${AWS_ACCESS_KEY_ID:-}"       ]] && printf 'export AWS_ACCESS_KEY_ID="%s"\n'       "$AWS_ACCESS_KEY_ID"
    [[ -n "${AWS_SECRET_ACCESS_KEY:-}"   ]] && printf 'export AWS_SECRET_ACCESS_KEY="%s"\n'   "$AWS_SECRET_ACCESS_KEY"
    [[ -n "${AWS_SESSION_TOKEN:-}"       ]] && printf 'export AWS_SESSION_TOKEN="%s"\n'       "$AWS_SESSION_TOKEN"
    printf 'export AWS_DEFAULT_REGION="%s"\n'  "${AWS_DEFAULT_REGION:-us-east-1}"
    printf '\n'
    printf 'export HYPRCONF_DOMAIN="%s"\n'     "$HYPRCONF_DOMAIN"
    printf 'export HYPRCONF_BUCKET="%s"\n'     "$HYPRCONF_BUCKET"
    printf 'export HYPRCONF_ZONE_ID="%s"\n'    "$HYPRCONF_ZONE_ID"
    printf 'export HYPRCONF_REPO="%s"\n'       "${HYPRCONF_REPO:-}"
  ) > "$CFG_FILE"
  log_ok "Config saved → $CFG_FILE"
}

# ── AWS authentication setup ──────────────────────────────────────────────────
_configure_aws() {
  if aws sts get-caller-identity &>/dev/null 2>&1; then
    log_ok "AWS credentials already valid."
    return 0
  fi

  printf '\n%s  [ AWS Authentication ]%s\n' "$AM" "$RS"
  printf '%s  1) Named profile (recommended — uses ~/.aws/config)\n' "$DM"
  printf '  2) Access key + secret (for accounts without local AWS config)%s\n' "$RS"
  printf '%s  Choice [1]: %s' "$WH" "$RS"
  local choice; read -r choice; choice="${choice:-1}"

  if [[ "$choice" == "2" ]]; then
    _ask        AWS_ACCESS_KEY_ID     "Access Key ID"
    _ask_secret AWS_SECRET_ACCESS_KEY "Secret Access Key"
    printf '%s  Session Token%s (press Enter to skip): ' "$DM$WH" "$DM"
    local tok; read -rs tok; printf '\n'
    [[ -n "$tok" ]] && { AWS_SESSION_TOKEN="$tok"; export AWS_SESSION_TOKEN; }
  else
    _ask AWS_PROFILE "AWS profile name" "default"
  fi

  aws sts get-caller-identity &>/dev/null 2>&1 \
    || log_die "AWS authentication failed. Check your credentials and try again."
  log_ok "AWS credentials valid."
}

# ── Route53 zone selection ────────────────────────────────────────────────────
_select_zone() {
  log_step "Fetching Route53 hosted zones..."

  local zones_raw
  zones_raw=$(aws route53 list-hosted-zones \
    --query 'HostedZones[].[Name,Id]' --output text 2>/dev/null) || {
    log_warn "Could not list hosted zones. Enter your Zone ID manually."
    _ask HYPRCONF_ZONE_ID "Route53 Hosted Zone ID"
    return
  }

  if [[ -z "$zones_raw" ]]; then
    log_warn "No hosted zones found in this AWS account."
    _ask HYPRCONF_ZONE_ID "Route53 Hosted Zone ID"
    return
  fi

  local names=() ids=()
  while IFS=$'\t' read -r name id; do
    names+=("${name%.}")               # strip trailing dot
    ids+=("${id##*/hostedzone/}")      # extract ID from /hostedzone/XXXX
  done <<< "$zones_raw"

  # Try to auto-match: find any zone whose name the domain ends with
  local match_idx=-1 i
  for i in "${!names[@]}"; do
    if [[ "$HYPRCONF_DOMAIN" == *.${names[$i]} ]] || \
       [[ "$HYPRCONF_DOMAIN" == "${names[$i]}" ]]; then
      match_idx=$i
    fi
  done

  if [[ $match_idx -ge 0 ]]; then
    printf '%s  Auto-matched zone: %s%s%s  (%s)\n' \
      "$GR" "$WH" "${names[$match_idx]}" "$RS" "${ids[$match_idx]}"
    printf '%s  Use this zone? [Y/n]: %s' "$DM$WH" "$RS"
    local yn; read -r yn
    if [[ "${yn,,}" != "n" ]]; then
      HYPRCONF_ZONE_ID="${ids[$match_idx]}"; export HYPRCONF_ZONE_ID
      return
    fi
  fi

  # Show menu
  printf '\n%s  Available hosted zones:%s\n' "$AM" "$RS"
  for i in "${!names[@]}"; do
    printf '%s  %2d)  %-35s %s%s\n' "$DM" $((i+1)) "${names[$i]}" "${ids[$i]}" "$RS"
  done
  printf '%s  Select zone number: %s' "$WH" "$RS"
  local sel; read -r sel
  local idx=$(( sel - 1 ))
  [[ $idx -ge 0 && $idx -lt ${#ids[@]} ]] \
    || log_die "Invalid selection."
  HYPRCONF_ZONE_ID="${ids[$idx]}"; export HYPRCONF_ZONE_ID
}

# ── Interactive environment configuration ─────────────────────────────────────
configure_env() {
  # Load saved config if present (vars already in env take priority)
  [[ -f "$CFG_FILE" ]] && source "$CFG_FILE"

  # If everything is already configured, skip all prompts
  if [[ -n "${HYPRCONF_DOMAIN:-}"   ]] && \
     [[ -n "${HYPRCONF_BUCKET:-}"   ]] && \
     [[ -n "${HYPRCONF_ZONE_ID:-}"  ]] && \
     aws sts get-caller-identity &>/dev/null 2>&1; then
    log_ok "Config loaded from $CFG_FILE"
    return 0
  fi

  [[ -t 0 ]] \
    || log_die "Configuration incomplete and no interactive terminal available.
       Export required variables or run 'hyprconf deploy' interactively."

  log_head "hyprconf deploy — first-time setup"
  printf '%s  Settings will be saved to: %s%s%s\n\n' \
    "$DM" "$WH" "$CFG_FILE" "$RS"

  command -v aws &>/dev/null \
    || log_die "AWS CLI not found. Install: https://aws.amazon.com/cli/"

  # AWS credentials
  _configure_aws

  # Region
  printf '\n%s  [ Region ]%s\n' "$AM" "$RS"
  printf '%s  Must be us-east-1 for CloudFront ACM certificates.%s\n' "$DM" "$RS"
  _ask AWS_DEFAULT_REGION "AWS region" "us-east-1"

  # Domain
  printf '\n%s  [ Install Domain ]%s\n' "$AM" "$RS"
  printf '%s  The domain where your install.sh will be served over HTTPS.\n' "$DM"
  printf '  Example: get.yourdomain.com%s\n' "$RS"
  while [[ -z "${HYPRCONF_DOMAIN:-}" ]]; do
    _ask HYPRCONF_DOMAIN "Domain"
  done

  # S3 bucket (suggest from domain)
  printf '\n%s  [ S3 Bucket ]%s\n' "$AM" "$RS"
  local suggested_bucket; suggested_bucket=$(printf '%s' "$HYPRCONF_DOMAIN" | tr '.' '-')
  _ask HYPRCONF_BUCKET "S3 bucket name (must be globally unique)" "$suggested_bucket"

  # Route53 zone
  printf '\n%s  [ Route53 Hosted Zone ]%s\n' "$AM" "$RS"
  if [[ -z "${HYPRCONF_ZONE_ID:-}" ]]; then
    _select_zone
  else
    log_ok "Zone ID already set: $HYPRCONF_ZONE_ID"
  fi

  # GitHub repo
  printf '\n%s  [ Repository URL ]%s\n' "$AM" "$RS"
  printf '%s  The repo cloned by your install.sh bootstrap.%s\n' "$DM" "$RS"
  local detected_repo
  detected_repo=$(git -C "$ROOT_DIR" remote get-url origin 2>/dev/null \
    | sed 's|^git@github\.com:|https://github.com/|; s|\.git$||' || true)
  _ask HYPRCONF_REPO "GitHub repo URL" "$detected_repo"

  printf '\n'
  _save_config
}

# ── Step 1: S3 bucket + install.sh upload ─────────────────────────────────────
# Pre-CDK: inject repo URL into install.sh before CDK deploys it.
prepare_install_sh() {
  log_head "Install Script"

  local install_src="$ROOT_DIR/install/install.sh"
  local install_deploy="$ROOT_DIR/install/install.sh.deploy"

  if [[ -n "${HYPRCONF_REPO:-}" ]] && [[ -f "$install_src" ]]; then
    log_step "Injecting repo URL into install.sh ..."
    sed "s|^readonly REPO_URL=.*|readonly REPO_URL=\"${HYPRCONF_REPO}\"|" \
      "$install_src" > "$install_deploy"
    log_ok "install.sh prepared (repo: ${HYPRCONF_REPO})"
  fi
}

# ── Step 2: Build web frontend ────────────────────────────────────────────────
build_web() {
  log_head "Web Frontend"

  local web_dir="$ROOT_DIR/web"

  if [[ ! -d "$web_dir" ]] || [[ ! -f "$web_dir/package.json" ]]; then
    log_warn "web/ directory not found — skipping frontend build."
    return 0
  fi

  if ! command -v npm &>/dev/null; then
    log_warn "npm not found — skipping frontend build. Install Node.js to deploy the web UI."
    return 0
  fi

  log_step "Installing web dependencies ..."
  (cd "$web_dir" && npm install --silent)

  log_step "Building web frontend ..."
  (cd "$web_dir" && npm run build)

  if [[ ! -d "$web_dir/dist" ]] || [[ ! -f "$web_dir/dist/index.html" ]]; then
    log_warn "Build produced no output — CDK will skip web asset deployment."
    return 0
  fi

  log_ok "Web frontend built → web/dist/"
}

# ── Step 3: Migrate legacy (non-CDK) resources ───────────────────────────────
# On the FIRST CDK deploy, existing AWS resources created by the old deploy.sh
# conflict with CDK trying to create them. This function detects and resolves
# those conflicts:
#   - S3 bucket → imported via importBucket=true context flag
#   - CloudFront Distribution → CNAME alias removed (CDK creates a new dist)
#   - CloudFront Function → orphaned (CDK auto-names its own)
#   - ACM cert / Route53 → CDK recreates them (no conflict)
migrate_legacy_resources() {
  # If the CDK stack already exists, no migration needed
  if aws cloudformation describe-stacks --stack-name HyprconfStack &>/dev/null 2>&1; then
    return 0
  fi

  log_step "First CDK deploy — checking for legacy resources to migrate ..."

  # Find existing CloudFront distribution by CNAME alias
  local dist_id
  dist_id=$(aws cloudfront list-distributions \
    --query "DistributionList.Items[?contains(Aliases.Items, '${HYPRCONF_DOMAIN}')].Id | [0]" \
    --output text 2>/dev/null || true)

  if [[ -n "$dist_id" && "$dist_id" != "None" && "$dist_id" != "null" ]]; then
    log_info "Legacy CloudFront distribution found: $dist_id"
    log_step "Removing domain alias from legacy distribution ..."

    local tmp_config etag config_json
    tmp_config=$(mktemp)

    # Get current distribution config
    aws cloudfront get-distribution-config --id "$dist_id" > "$tmp_config" 2>/dev/null \
      || { rm -f "$tmp_config"; log_warn "Could not fetch distribution config — skipping migration."; return 0; }

    # Extract ETag and modify config to remove CNAME alias + custom cert
    etag=$(python3 -c "
import json, sys
d = json.load(open('$tmp_config'))
print(d['ETag'])
" 2>/dev/null)
    config_json=$(python3 -c "
import json, sys
d = json.load(open('$tmp_config'))['DistributionConfig']
d['Aliases'] = {'Quantity': 0, 'Items': []}
d['ViewerCertificate'] = {
    'CloudFrontDefaultCertificate': True,
    'MinimumProtocolVersion': 'TLSv1'
}
print(json.dumps(d))
" 2>/dev/null)

    printf '%s' "$config_json" > "$tmp_config"

    # Update distribution to remove CNAME alias
    aws cloudfront update-distribution \
      --id "$dist_id" \
      --if-match "$etag" \
      --distribution-config "file://$tmp_config" &>/dev/null \
      || { rm -f "$tmp_config"; log_warn "Could not update distribution — you may need to remove the CNAME alias manually."; return 0; }

    rm -f "$tmp_config"
    log_ok "Removed domain alias from legacy distribution."
    log_info "Waiting for CloudFront update to propagate ..."

    # Wait for the distribution update to deploy (required before CDK can
    # create a new distribution with the same CNAME).
    local wait_start=$SECONDS max_wait=900 poll_interval=15
    while true; do
      local status
      status=$(aws cloudfront get-distribution --id "$dist_id" \
        --query 'Distribution.Status' --output text 2>/dev/null || echo "Unknown")

      if [[ "$status" == "Deployed" ]]; then
        log_ok "Legacy distribution updated — CNAME alias removed."
        break
      fi

      if (( SECONDS - wait_start > max_wait )); then
        log_warn "Distribution update still in progress after $((max_wait/60))m."
        log_warn "CDK deploy may fail if the alias hasn't been released yet."
        break
      fi

      printf '\r%s  ─ Waiting for distribution update (%ds elapsed, status: %s) ...%s' \
        "$DM" $((SECONDS - wait_start)) "$status" "$RS"
      sleep "$poll_interval"
    done
    printf '\n'

    # Save old distribution ID for later cleanup
    state_set LEGACY_DISTRIBUTION_ID "$dist_id"
    log_info "Old distribution $dist_id is orphaned. Clean up later with:"
    log_info "  aws cloudfront disable-distribution --id $dist_id"
    log_info "  aws cloudfront delete-distribution --id $dist_id --if-match <etag>"
  fi

  log_ok "Legacy migration check complete."
}

# ── Step 4: CDK Deploy ────────────────────────────────────────────────────────
cdk_deploy() {
  log_head "CDK Deploy"

  local cdk_dir="$INFRA_DIR/cdk"

  if [[ ! -d "$cdk_dir" ]]; then
    log_die "infra/cdk/ directory not found."
  fi

  command -v npx &>/dev/null || log_die "npx not found. Install Node.js."

  # Ensure CDK dependencies are installed
  if [[ ! -d "$cdk_dir/node_modules" ]]; then
    log_step "Installing CDK dependencies ..."
    (cd "$cdk_dir" && npm install --silent)
  fi

  # Resolve AWS account ID for CDK env
  local account_id
  account_id=$(aws sts get-caller-identity --query 'Account' --output text 2>/dev/null) \
    || log_die "Could not resolve AWS account ID."
  export CDK_DEFAULT_ACCOUNT="$account_id"

  # Check if CDK is bootstrapped in this account/region
  local region="${AWS_DEFAULT_REGION:-us-east-1}"
  log_step "Checking CDK bootstrap status ..."
  if ! aws ssm get-parameter \
    --name "/cdk-bootstrap/hnb659fds/version" \
    --region "$region" &>/dev/null 2>&1; then
    log_step "CDK not bootstrapped — running cdk bootstrap ..."
    (cd "$cdk_dir" && npx cdk bootstrap "aws://${account_id}/${region}")
    log_ok "CDK bootstrapped."
  else
    log_ok "CDK already bootstrapped."
  fi

  log_step "Deploying HyprconfStack via CDK ..."

  # Auto-detect if bucket already exists (created by legacy deploy.sh)
  local import_bucket="false"
  if aws s3api head-bucket --bucket "$HYPRCONF_BUCKET" 2>/dev/null; then
    import_bucket="true"
    log_info "Existing bucket detected — importing into CDK stack."
  fi

  (cd "$cdk_dir" && npx cdk deploy \
    --require-approval never \
    --context "domain=${HYPRCONF_DOMAIN}" \
    --context "bucket=${HYPRCONF_BUCKET}" \
    --context "zoneId=${HYPRCONF_ZONE_ID}" \
    --context "repoUrl=${HYPRCONF_REPO:-}" \
    --context "importBucket=${import_bucket}" \
    --outputs-file "$CFG_DIR/cdk-outputs.json" \
    2>&1)

  log_ok "CDK deploy complete."

  # Extract outputs for display
  if [[ -f "$CFG_DIR/cdk-outputs.json" ]]; then
    local dist_id dist_domain
    dist_id=$(python3 -c "
import json, sys
d = json.load(open('${CFG_DIR}/cdk-outputs.json'))
s = d.get('HyprconfStack', {})
print(s.get('DistributionId', ''))
" 2>/dev/null || true)
    dist_domain=$(python3 -c "
import json, sys
d = json.load(open('${CFG_DIR}/cdk-outputs.json'))
s = d.get('HyprconfStack', {})
print(s.get('DistributionDomain', ''))
" 2>/dev/null || true)

    # Save to state file for backward compatibility
    [[ -n "$dist_id" ]] && state_set DISTRIBUTION_ID "$dist_id"
    [[ -n "$dist_domain" ]] && state_set DISTRIBUTION_DOMAIN "$dist_domain"
  fi
}

# ── Cleanup temporary files ───────────────────────────────────────────────────
cleanup() {
  rm -f "$ROOT_DIR/install/install.sh.deploy"
}

# ── Entry ─────────────────────────────────────────────────────────────────────
main() {
  # shellcheck source=../assets/banner.sh
  source "$ROOT_DIR/assets/banner.sh" 2>/dev/null || true
  print_banner

  local web_only=false
  if [[ "${1:-}" == "web" ]]; then
    web_only=true
  fi

  configure_env
  trap cleanup EXIT

  if $web_only; then
    build_web
    migrate_legacy_resources
    cdk_deploy
  else
    prepare_install_sh
    build_web
    migrate_legacy_resources
    cdk_deploy
  fi

  printf '\n%s  ──────────────────────────────────────────────────────────────%s\n' "$GR" "$RS"
  printf '%s  ✔  Deploy complete!%s\n' "$GR" "$RS"
  printf '%s  ──────────────────────────────────────────────────────────────%s\n\n' "$GR" "$RS"
  printf '%s  Install URL:   %shttps://%s%s\n'                       "$DM" "$AM" "$HYPRCONF_DOMAIN" "$RS"
  printf '%s  Web frontend:  %shttps://%s%s\n'                       "$DM" "$AM" "$HYPRCONF_DOMAIN" "$RS"
  printf '%s  One-liner:     %sbash <(curl -fsSL https://%s)%s\n'    "$DM" "$WH" "$HYPRCONF_DOMAIN" "$RS"
  printf '%s  Config file:   %s%s%s\n'                                "$DM" "$DM" "$CFG_FILE"        "$RS"
  printf '%s  CDK outputs:   %s%s/cdk-outputs.json%s\n\n'             "$DM" "$DM" "$CFG_DIR"          "$RS"
}

main "$@"
