/* Generated by hyprconf from Omarchy's active theme — do not edit: the
   theme-set hook rewrites this on every `omarchy theme set`. */
/* Rendered by Omarchy's omarchy-theme-set-templates from the user template
   ~/.config/omarchy/themed/userChrome.css.tpl (hyprconf's themed/) into
   ~/.local/state/omarchy/current/theme/userChrome.css, from the theme's
   colors.toml. lib/hyprconf/firefox_theme.py copies it into each profile and
   reads the theme mode back from --hyprconf-theme-mode. */
:root {
  --hyprconf-theme-mode: {{ mode }};
  /* Firefox's theme variables. On 154 the --lwt-* ones are inert — the
     built-in Dark/Light themes user.js activates are inApp, so
     :root[lwtheme] never turns on — and six of the names below are gone
     from Firefox entirely. The direct rules further down paint the
     chrome; these are kept for other themes and older builds. */
  --lwt-accent-color: {{ background }} !important;
  --lwt-text-color: {{ foreground }} !important;
  --toolbar-bgcolor: {{ background }} !important;
  --toolbar-color: {{ foreground }} !important;
  --tab-selected-bgcolor: {{ lighter_background }} !important;
  --toolbar-field-background-color: {{ dark_background }} !important;
  --toolbar-field-color: {{ foreground }} !important;
  --toolbar-field-focus-background-color: {{ dark_background }} !important;
  --toolbar-field-focus-color: {{ foreground }} !important;
  --lwt-sidebar-background-color: {{ background }} !important;
  --lwt-sidebar-text-color: {{ foreground }} !important;
  --focus-outline-color: {{ accent }} !important;
}
/* The chrome itself, by the ids Firefox has kept stable for years — paints
   the same colours even when the user later picks another theme (or none),
   when the variables above would go unused. */
#navigator-toolbox, #TabsToolbar, #nav-bar, #PersonalToolbar {
  background-color: {{ background }} !important;
  color: {{ foreground }} !important;
}
#urlbar-background, #searchbar {
  background-color: {{ dark_background }} !important;
}
.tab-background[selected] {
  background-color: {{ lighter_background }} !important;
}
#sidebar-box, #sidebar-main {
  background-color: {{ background }} !important;
  color: {{ foreground }} !important;
}
