/**
 * Build-time script: reads the canonical hyprconf version from the Python
 * package (`__init__.py`) and generates `src/generated/version.ts`, so the web
 * frontend's displayed version can never drift from the shipped release.
 *
 * Run: npm run generate-version (auto-runs as part of `build` / `dev`).
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Single source of truth for the version across the whole suite.
const INIT_PY = path.resolve(
  __dirname,
  '../../stow/hypr/.local/lib/hyprconf/__init__.py'
);
const OUTPUT_FILE = path.resolve(__dirname, '../src/generated/version.ts');

function main(): void {
  const src = fs.readFileSync(INIT_PY, 'utf-8');
  const match = src.match(/__version__\s*=\s*["']([^"']+)["']/);
  if (!match) {
    throw new Error(`Could not find __version__ in ${INIT_PY}`);
  }
  const version = match[1];

  const output =
    `// AUTO-GENERATED by scripts/generate-version.ts — do not edit by hand.\n` +
    `// Source of truth: stow/hypr/.local/lib/hyprconf/__init__.py\n` +
    `export const VERSION = '${version}';\n`;

  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');
  console.log(`Generated ${OUTPUT_FILE} with version ${version}`);
}

main();
