# Ayu Mirage
foreground            #cccac2
background            #212733
selection_foreground  #cccac2
selection_background  #343f4c

url_color #5ccfe6

# black
color0  #1a1f29
color8  #5c6773

# red
color1  #f28779
color9  #f28779

# green
color2  #bae67e
color10 #bae67e

# yellow
color3  #ffd580
color11 #ffd580

# blue
color4  #5ccfe6
color12 #5ccfe6

# magenta
color5  #a37acc
color13 #a37acc

# cyan
color6  #95e6cb
color14 #95e6cb

# white
color7  #cccac2
color15 #e6e1cf

# Cursor colors
cursor            #ffcc66
cursor_text_color background

# Tab bar colors
active_tab_foreground   #212733
active_tab_background   #5ccfe6
inactive_tab_foreground #212733
inactive_tab_background #5c6773

# Marks
mark1_foreground #212733
mark1_background #f28779

# Splits/Windows
active_border_color   #ffcc66
inactive_border_color #5c6773
