# Ayu Dark
foreground            #bfbdb6
background            #0d1017
selection_foreground  #bfbdb6
selection_background  #253340

url_color #95e6cb

# black
color0  #11141a
color8  #626a73

# red
color1  #f07178
color9  #f07178

# green
color2  #7fd962
color10 #7fd962

# yellow
color3  #e6b450
color11 #e6b450

# blue
color4  #59c2ff
color12 #59c2ff

# magenta
color5  #d2a6ff
color13 #d2a6ff

# cyan
color6  #95e6cb
color14 #95e6cb

# white
color7  #bfbdb6
color15 #e6e1cf

# Cursor colors
cursor            #e6b673
cursor_text_color background

# Tab bar colors
active_tab_foreground   #0d1017
active_tab_background   #59c2ff
inactive_tab_foreground #0d1017
inactive_tab_background #626a73

# Marks
mark1_foreground #0d1017
mark1_background #f07178

# Splits/Windows
active_border_color   #e6b673
inactive_border_color #626a73
