# Catppuccin Frappe
foreground            #c6d0f5
background            #303446
selection_foreground  #c6d0f5
selection_background  #51576d

url_color #99d1db

# black
color0  #51576d
color8  #626880

# red
color1  #e78284
color9  #e78284

# green
color2  #a6d189
color10 #a6d189

# yellow
color3  #e5c890
color11 #e5c890

# blue
color4  #8caaee
color12 #8caaee

# magenta
color5  #f4b8e4
color13 #f4b8e4

# cyan
color6  #99d1db
color14 #99d1db

# white
color7  #b5bfe2
color15 #a5adce

# Cursor colors
cursor            #f2d5cf
cursor_text_color background

# Tab bar colors
active_tab_foreground   #303446
active_tab_background   #ca9ee6
inactive_tab_foreground #303446
inactive_tab_background #626880

# Marks
mark1_foreground #303446
mark1_background #e78284

# Splits/Windows
active_border_color   #f2d5cf
inactive_border_color #626880
