# Catppuccin Macchiato
foreground            #cad3f5
background            #24273a
selection_foreground  #cad3f5
selection_background  #494d64

url_color #91d7e3

# black
color0  #494d64
color8  #5b6078

# red
color1  #ed8796
color9  #ed8796

# green
color2  #a6da95
color10 #a6da95

# yellow
color3  #eed49f
color11 #eed49f

# blue
color4  #8aadf4
color12 #8aadf4

# magenta
color5  #f5bde6
color13 #f5bde6

# cyan
color6  #91d7e3
color14 #91d7e3

# white
color7  #b8c0e0
color15 #a5adcb

# Cursor colors
cursor            #f4dbd6
cursor_text_color background

# Tab bar colors
active_tab_foreground   #24273a
active_tab_background   #c6a0f6
inactive_tab_foreground #24273a
inactive_tab_background #5b6078

# Marks
mark1_foreground #24273a
mark1_background #ed8796

# Splits/Windows
active_border_color   #f4dbd6
inactive_border_color #5b6078
