# Cyberdream
foreground            #ffffff
background            #16181a
selection_foreground  #ffffff
selection_background  #3c3c3c

url_color #5ef1ff

# black
color0  #16181a
color8  #3d3d3d

# red
color1  #ff6e5e
color9  #ff6e5e

# green
color2  #5eff6c
color10 #5eff6c

# yellow
color3  #f1ff5e
color11 #f1ff5e

# blue
color4  #5ea1ff
color12 #5ea1ff

# magenta
color5  #bd5eff
color13 #bd5eff

# cyan
color6  #5ef1ff
color14 #5ef1ff

# white
color7  #ffffff
color15 #ffffff

# Cursor colors
cursor            #ffffff
cursor_text_color background

# Tab bar colors
active_tab_foreground   #16181a
active_tab_background   #bd5eff
inactive_tab_foreground #16181a
inactive_tab_background #3d3d3d

# Marks
mark1_foreground #16181a
mark1_background #ff6e5e

# Splits/Windows
active_border_color   #ffffff
inactive_border_color #3d3d3d
