# Kanagawa Wave
foreground            #dcd7ba
background            #1f1f28
selection_foreground  #dcd7ba
selection_background  #2d4f67

url_color #7aa89f

# black
color0  #16161d
color8  #727169

# red
color1  #c34043
color9  #e82424

# green
color2  #76946a
color10 #98bb6c

# yellow
color3  #c0a36e
color11 #e6c384

# blue
color4  #7e9cd8
color12 #7fb4ca

# magenta
color5  #957fb8
color13 #938aa9

# cyan
color6  #6a9589
color14 #7aa89f

# white
color7  #c8c093
color15 #dcd7ba

# Cursor colors
cursor            #c8c093
cursor_text_color background

# Tab bar colors
active_tab_foreground   #1f1f28
active_tab_background   #7e9cd8
inactive_tab_foreground #1f1f28
inactive_tab_background #727169

# Marks
mark1_foreground #1f1f28
mark1_background #c34043

# Splits/Windows
active_border_color   #c8c093
inactive_border_color #727169
