# Monokai Pro
foreground            #fcfcfa
background            #2d2a2e
selection_foreground  #fcfcfa
selection_background  #403e41

url_color #78dce8

# black
color0  #403e41
color8  #727072

# red
color1  #ff6188
color9  #ff6188

# green
color2  #a9dc76
color10 #a9dc76

# yellow
color3  #ffd866
color11 #ffd866

# blue
color4  #fc9867
color12 #fc9867

# magenta
color5  #ab9df2
color13 #ab9df2

# cyan
color6  #78dce8
color14 #78dce8

# white
color7  #fcfcfa
color15 #ffffff

# Cursor colors
cursor            #fcfcfa
cursor_text_color background

# Tab bar colors
active_tab_foreground   #2d2a2e
active_tab_background   #ff6188
inactive_tab_foreground #2d2a2e
inactive_tab_background #727072

# Marks
mark1_foreground #2d2a2e
mark1_background #ff6188

# Splits/Windows
active_border_color   #fcfcfa
inactive_border_color #727072
