# Material Palenight
foreground            #a6accd
background            #292d3e
selection_foreground  #a6accd
selection_background  #444267

url_color #89ddff

# black
color0  #292d3e
color8  #676e95

# red
color1  #f07178
color9  #f07178

# green
color2  #c3e88d
color10 #c3e88d

# yellow
color3  #ffcb6b
color11 #ffcb6b

# blue
color4  #82aaff
color12 #82aaff

# magenta
color5  #c792ea
color13 #c792ea

# cyan
color6  #89ddff
color14 #89ddff

# white
color7  #d0d0d0
color15 #ffffff

# Cursor colors
cursor            #a6accd
cursor_text_color background

# Tab bar colors
active_tab_foreground   #292d3e
active_tab_background   #c792ea
inactive_tab_foreground #292d3e
inactive_tab_background #676e95

# Marks
mark1_foreground #292d3e
mark1_background #f07178

# Splits/Windows
active_border_color   #a6accd
inactive_border_color #676e95
