# Rose Pine Moon
foreground            #e0def4
background            #232136
selection_foreground  #e0def4
selection_background  #44415a

url_color #9ccfd8

# black
color0  #393552
color8  #6e6a86

# red
color1  #eb6f92
color9  #eb6f92

# green
color2  #3e8fb0
color10 #3e8fb0

# yellow
color3  #f6c177
color11 #f6c177

# blue
color4  #9ccfd8
color12 #9ccfd8

# magenta
color5  #c4a7e7
color13 #c4a7e7

# cyan
color6  #ea9a97
color14 #ea9a97

# white
color7  #e0def4
color15 #e0def4

# Cursor colors
cursor            #e0def4
cursor_text_color background

# Tab bar colors
active_tab_foreground   #232136
active_tab_background   #c4a7e7
inactive_tab_foreground #232136
inactive_tab_background #6e6a86

# Marks
mark1_foreground #232136
mark1_background #eb6f92

# Splits/Windows
active_border_color   #e0def4
inactive_border_color #6e6a86
