# Tokyo Night Storm
foreground            #c0caf5
background            #24283b
selection_foreground  #c0caf5
selection_background  #364a82

url_color #7dcfff

# black
color0  #1d202f
color8  #414868

# red
color1  #f7768e
color9  #ff9e9e

# green
color2  #9ece6a
color10 #b9f27c

# yellow
color3  #e0af68
color11 #ffc777

# blue
color4  #7aa2f7
color12 #7aa2f7

# magenta
color5  #bb9af7
color13 #c9b8fc

# cyan
color6  #7dcfff
color14 #a9daff

# white
color7  #a9b1d6
color15 #c0caf5

# Cursor colors
cursor            #c0caf5
cursor_text_color background

# Tab bar colors
active_tab_foreground   #24283b
active_tab_background   #7aa2f7
inactive_tab_foreground #24283b
inactive_tab_background #414868

# Marks
mark1_foreground #24283b
mark1_background #f7768e

# Splits/Windows
active_border_color   #c0caf5
inactive_border_color #414868
