# Tokyo Night Moon
foreground            #c8d3f5
background            #222436
selection_foreground  #c8d3f5
selection_background  #2d3f76

url_color #86e1fc

# black
color0  #1b1d2b
color8  #444a73

# red
color1  #ff757f
color9  #ff8b92

# green
color2  #c3e88d
color10 #d2f5a6

# yellow
color3  #ffc777
color11 #ffd999

# blue
color4  #82aaff
color12 #82aaff

# magenta
color5  #c099ff
color13 #cfb3ff

# cyan
color6  #86e1fc
color14 #b4f9f8

# white
color7  #828bb8
color15 #c8d3f5

# Cursor colors
cursor            #c8d3f5
cursor_text_color background

# Tab bar colors
active_tab_foreground   #222436
active_tab_background   #82aaff
inactive_tab_foreground #222436
inactive_tab_background #444a73

# Marks
mark1_foreground #222436
mark1_background #ff757f

# Splits/Windows
active_border_color   #c8d3f5
inactive_border_color #444a73
