monitor = HDMI-A-2,4096x2160@119.88Hz,-2048x540,2
monitor = DP-2,3840x2160@59.99700,0x0,2,transform,2
monitor = DP-3,3840x2160@240.00Hz,0x1080,2

workspace = 1,monitor:DP-3
workspace = 4,monitor:DP-3
workspace = 2,monitor:HDMI-A-2
workspace = 5,monitor:HDMI-A-2
workspace = 3,monitor:DP-2
workspace = 6,monitor:DP-2
