#!/usr/bin/env bash
set -euo pipefail

readonly DISPLAY="eDP-1"

DISABLED=$(hyprctl monitors | awk -v m="$DISPLAY" '
  $0 ~ "Monitor " m {flag=1}
  flag && $1=="disabled:" {print $2; exit}
')

if [[ "$DISABLED" == "false" ]]; then
    echo "$DISPLAY is enabled, disabling..."
    hyprctl keyword monitor "$DISPLAY,disable"
else
    echo "$DISPLAY is disabled, enabling..."
    hyprctl keyword monitor "$DISPLAY,1920x1200,auto,1"
fi
