"""Tests for hyprconf.firefox_theme — Omarchy's rendered userChrome.css into profiles.

Omarchy ships no Firefox theming (omarchy-theme-set-browser is Chromium-only).
The overlay's bridge is a user template, themed/userChrome.css.tpl, which
Omarchy's own omarchy-theme-set-templates renders into
~/.local/state/omarchy/current/theme/userChrome.css on every theme set. This
module must: find the right profiles the way Firefox does (every [Install…]
Default — each build honours only its own section — falling back to a Profile
Default=1, then the first profile), copy that rendered file byte-for-byte into
each profile, merge — never clobber — the profile's user.js with prefs that
follow the mode the file declares, never render anything itself (a missing
render is an error naming `omarchy theme refresh`, the command that renders
the current theme's templates), and be idempotent, since the hook re-runs on
every theme switch and every install.sh run.

Hermetic: HOME relocated, PATH pinned to a fake-bins dir plus /usr/bin, with
a recording stub of every Omarchy theme command first on it (/usr/bin holds
a copy of every omarchy-* command, so the stubs are what make "never runs"
provable), notify() replaced.
"""

from __future__ import annotations

import errno
import os
import re
import stat
import subprocess
from pathlib import Path

import pytest
from hyprconf import firefox_theme as ft

REPO_ROOT = Path(__file__).resolve().parents[2]
TEMPLATE = REPO_ROOT / "themed" / "userChrome.css.tpl"
HOOK = REPO_ROOT / "hooks" / "theme-set.d" / "10-hyprconf"

# What Omarchy renders from the template for a dark theme — CRLF and a
# non-ASCII byte included, so "byte-for-byte" is really tested.
CSS_DARK = (
    b"/* Generated by hyprconf from Omarchy's active theme \xe2\x80\x94 do not edit */\r\n"
    b":root {\r\n  --hyprconf-theme-mode: dark;\r\n"
    b"  --toolbar-bgcolor: #16242d !important;\r\n}\r\n"
)
CSS_LIGHT = CSS_DARK.replace(b"dark", b"light").replace(b"#16242d", b"#eff1f5")

PALETTE = {
    "mode": "dark",
    "background": "#16242d",
    "foreground": "#d6e2ee",
    "accent": "#8bc9eb",
    "dark_background": "#101b21",
    "lighter_background": "#1b2d40",
    "red": "#ff0000",
}


def _ini(root: Path, body: str) -> Path:
    ini = root / "profiles.ini"
    ini.parent.mkdir(parents=True, exist_ok=True)
    ini.write_text(body)
    return ini


@pytest.fixture(autouse=True)
def notices(monkeypatch: pytest.MonkeyPatch) -> list[str]:
    """What main() announced. notify() runs omarchy-notification-send when it
    is on PATH, so it is replaced for every test, not per test."""
    sent: list[str] = []
    monkeypatch.setattr(ft, "notify", sent.append)
    return sent


# Omarchy's theme machinery — what renders the template and swaps the theme.
# The bridge must never call any of it: omarchy-theme-set-templates writes
# only into omarchy-theme-set's own next-theme staging dir under its lock
# (bin/omarchy-theme-set on Omarchy 4.0.2-1: `flock 9`, the
# omarchy-theme-set-templates call, then the mv of next-theme over theme),
# and the hook runs INSIDE a theme set.
THEME_COMMANDS = ("omarchy-theme-set-templates", "omarchy-theme-refresh", "omarchy-theme-set")


@pytest.fixture(autouse=True)
def hermetic(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> dict[str, Path]:
    """A relocated HOME and a fake-bins dir first on a pinned PATH, holding a
    recording stub of every Omarchy theme command so a test can prove none
    of them ran."""
    home = tmp_path / "home"
    bins = tmp_path / "bins"
    for d in (home, bins):
        d.mkdir()
    monkeypatch.setenv("HOME", str(home))
    monkeypatch.setenv("PATH", f"{bins}:/usr/bin:/bin")
    calls = tmp_path / "calls"
    calls.write_text("")
    for name in THEME_COMMANDS:
        stub = bins / name
        stub.write_text(f'#!/usr/bin/env bash\nprintf \'%s\\n\' "{name} $*" >> "{calls}"\nexit 0\n')
        stub.chmod(0o755)
    return {"home": home, "bins": bins, "calls": calls}


def _theme(env: dict[str, Path], rendered: bytes | None = CSS_DARK) -> Path:
    """The active theme as omarchy-theme-set leaves it: colors.toml plus the
    rendered stylesheet (omarchy-theme-set-templates renders it into
    omarchy-theme-set's staging dir, whose mv swaps it in)."""
    theme = env["home"] / ft.THEME_DIR_REL
    theme.mkdir(parents=True, exist_ok=True)
    (theme / "colors.toml").write_text('mode = "dark"\nbackground = "#16242d"\n')
    if rendered is not None:
        (theme / ft.RENDERED_NAME).write_bytes(rendered)
    return theme


def _profile(env: dict[str, Path]) -> Path:
    ff = env["home"] / ".config" / "mozilla" / "firefox"
    profile = ff / "abc.default-release"
    profile.mkdir(parents=True, exist_ok=True)
    _ini(ff, "[Profile0]\nPath=abc.default-release\nIsRelative=1\nDefault=1\n")
    return profile


def _two_install_profiles(env: dict[str, Path]) -> tuple[Path, Path]:
    """A profiles.ini carrying two [Install…] sections — the package and a
    Developer Edition, each naming its own profile."""
    release = _profile(env)
    ff = release.parent
    dev = ff / "dev.dev-edition-default"
    dev.mkdir()
    _ini(
        ff,
        "[Profile0]\nPath=abc.default-release\nIsRelative=1\n\n"
        "[Profile1]\nPath=dev.dev-edition-default\nIsRelative=1\n\n"
        "[InstallAAAA]\nDefault=abc.default-release\n\n"
        "[InstallBBBB]\nDefault=dev.dev-edition-default\n",
    )
    return release, dev


# ---------------------------------------------------------------------------
# Profile discovery
# ---------------------------------------------------------------------------


def test_install_default_wins_over_profile_default(tmp_path: Path) -> None:
    """Modern Firefox records the profile it last used per install; that is
    the one the user sees, even when an older [Profile] still says Default=1."""
    (tmp_path / "new.default-release").mkdir()
    (tmp_path / "old.default").mkdir()
    ini = _ini(
        tmp_path,
        "[Profile0]\nName=default-release\nIsRelative=1\nPath=new.default-release\n\n"
        "[Install4F96]\nDefault=new.default-release\nLocked=1\n\n"
        "[Profile1]\nName=default\nIsRelative=1\nPath=old.default\nDefault=1\n",
    )
    assert ft.default_profiles(ini) == [tmp_path / "new.default-release"]


def test_every_install_section_names_its_own_profile(tmp_path: Path) -> None:
    """Two builds sharing one profiles.ini (the package and, say, Developer
    Edition) each keep an [Install<hash of their install dir>] section and
    honour only their own, so both profiles must be themed — there is no
    telling which build starts next."""
    (tmp_path / "release.default-release").mkdir()
    (tmp_path / "dev.dev-edition-default").mkdir()
    ini = _ini(
        tmp_path,
        "[Profile0]\nPath=release.default-release\nIsRelative=1\n\n"
        "[Profile1]\nPath=dev.dev-edition-default\nIsRelative=1\n\n"
        "[Install4F96D1932A9F858E]\nDefault=release.default-release\nLocked=1\n\n"
        "[Install11457493C5A56847]\nDefault=dev.dev-edition-default\nLocked=1\n",
    )
    assert ft.default_profiles(ini) == [
        tmp_path / "release.default-release",
        tmp_path / "dev.dev-edition-default",
    ]


def test_install_sections_naming_the_same_profile_are_deduplicated(tmp_path: Path) -> None:
    (tmp_path / "one.default-release").mkdir()
    ini = _ini(
        tmp_path,
        "[Profile0]\nPath=one.default-release\nIsRelative=1\nDefault=1\n\n"
        "[InstallAAAA]\nDefault=one.default-release\n\n"
        "[InstallBBBB]\nDefault=one.default-release\n",
    )
    assert ft.default_profiles(ini) == [tmp_path / "one.default-release"]


def test_profile_default_flag_then_first_profile_when_no_install_section(tmp_path: Path) -> None:
    ini = _ini(
        tmp_path,
        "[Profile0]\nPath=a.default\nIsRelative=1\n\n[Profile1]\nPath=b.default\nIsRelative=1\nDefault=1\n",
    )
    assert ft.default_profiles(ini) == [tmp_path / "b.default"]
    ini2 = _ini(tmp_path / "second", "[Profile0]\nPath=only.default\nIsRelative=1\n")
    assert ft.default_profiles(ini2) == [tmp_path / "second" / "only.default"]
    # An [Install] pointing at a profile that no longer exists is not a default.
    (tmp_path / "third" / "live.default").mkdir(parents=True)
    ini3 = _ini(
        tmp_path / "third",
        "[Profile0]\nPath=live.default\nIsRelative=1\n\n[InstallDEAD]\nDefault=gone.default\n",
    )
    assert ft.default_profiles(ini3) == [tmp_path / "third" / "live.default"]


def test_absolute_profile_path(tmp_path: Path) -> None:
    ini = _ini(tmp_path, f"[Profile0]\nPath={tmp_path}/elsewhere\nIsRelative=0\nDefault=1\n")
    assert ft.default_profiles(ini) == [tmp_path / "elsewhere"]
    (tmp_path / "abs").mkdir()
    ini2 = _ini(tmp_path / "other", f"[InstallABCD]\nDefault={tmp_path}/abs\n")
    assert ft.default_profiles(ini2) == [tmp_path / "abs"]


def test_unparseable_or_empty_ini_yields_nothing(tmp_path: Path) -> None:
    assert ft.default_profiles(_ini(tmp_path, "[General]\nVersion=2\n")) == []
    assert ft.default_profiles(_ini(tmp_path / "bad", "not an ini\n[[[")) == []


def test_profile_inis_finds_firefox_and_librewolf_under_home(tmp_path: Path) -> None:
    _ini(tmp_path / ".config" / "mozilla" / "firefox", "[Profile0]\nPath=x\n")
    _ini(tmp_path / ".librewolf", "[Profile0]\nPath=y\n")
    found = ft.profile_inis(tmp_path)
    assert [b for b, _ in found] == ["firefox", "librewolf"]


# ---------------------------------------------------------------------------
# The rendered stylesheet -> mode and prefs
# ---------------------------------------------------------------------------


def test_rendered_mode_is_what_the_stylesheet_declares() -> None:
    """The template carries `--hyprconf-theme-mode: {{ mode }}` — Omarchy's
    own resolution (mode key, theme_type, legacy light.mode, luminance) — so
    the mode is read back from the rendered file, never re-derived here."""
    assert ft.rendered_mode(CSS_DARK) == "dark"
    assert ft.rendered_mode(CSS_LIGHT) == "light"
    assert ft.rendered_mode(b":root {\n  --hyprconf-theme-mode:light ;\n}\n") == "light"
    # A stylesheet with no declaration (a user's own template) is treated as dark.
    assert ft.rendered_mode(b":root { --toolbar-bgcolor: #000; }\n") == "dark"
    assert ft.rendered_mode(b"\xff\xfe not utf-8") == "dark"


def test_theme_prefs_follow_the_mode() -> None:
    dark = ft.theme_prefs("dark")
    light = ft.theme_prefs("light")
    assert dark["toolkit.legacyUserProfileCustomizations.stylesheets"] is True
    # activeThemeID forces the light/dark colour scheme — on FF 154 the
    # built-in ids are inApp, so it never unlocks the --lwt-* block; the
    # template's direct selectors paint (AGENTS.md › Known quirks).
    assert dark["extensions.activeThemeID"] == "firefox-compact-dark@mozilla.org"
    assert light["extensions.activeThemeID"] == "firefox-compact-light@mozilla.org"
    assert dark["ui.systemUsesDarkTheme"] == 1 and light["ui.systemUsesDarkTheme"] == 0
    # browser.theme.{content,toolbar}-theme are what Firefox writes from the
    # active theme, not inputs — exactly three prefs are managed.
    assert (
        set(dark)
        == set(light)
        == {
            "toolkit.legacyUserProfileCustomizations.stylesheets",
            "extensions.activeThemeID",
            "ui.systemUsesDarkTheme",
        }
    )


def test_format_pref_literals() -> None:
    assert ft.format_pref("a.b", True) == 'user_pref("a.b", true);'
    assert ft.format_pref("a.b", 0) == 'user_pref("a.b", 0);'
    assert ft.format_pref("a.b", 'say "hi"') == 'user_pref("a.b", "say \\"hi\\"");'


# ---------------------------------------------------------------------------
# user.js merge
# ---------------------------------------------------------------------------


def test_merge_user_js_replaces_managed_keys_and_keeps_the_rest(tmp_path: Path) -> None:
    user_js = tmp_path / "user.js"
    user_js.write_text(
        "// mine\n"
        'user_pref("browser.startup.homepage", "about:blank");\n'
        'user_pref("ui.systemUsesDarkTheme", 0);\n'
    )
    ft.merge_user_js(user_js, {"ui.systemUsesDarkTheme": 1, "x.y": True})
    body = user_js.read_text()
    assert "// mine" in body
    assert 'user_pref("browser.startup.homepage", "about:blank");' in body
    assert body.count("ui.systemUsesDarkTheme") == 1
    assert 'user_pref("ui.systemUsesDarkTheme", 1);' in body
    assert 'user_pref("x.y", true);' in body


def test_merge_user_js_creates_the_file(tmp_path: Path) -> None:
    ft.merge_user_js(tmp_path / "user.js", {"a": 1})
    assert (tmp_path / "user.js").read_text() == 'user_pref("a", 1);\n'


def test_merge_user_js_recognises_single_quoted_keys() -> None:
    """Firefox's pref parser takes either quote style; a single-quoted managed
    pref must be replaced, not left behind as a duplicate."""
    assert ft._pref_key("user_pref('ui.systemUsesDarkTheme', 0);") == "ui.systemUsesDarkTheme"
    assert ft._pref_key('user_pref("ui.systemUsesDarkTheme", 0);') == "ui.systemUsesDarkTheme"
    assert ft._pref_key("user_pref(\"a\", 'x');") == "a"
    assert ft._pref_key('// user_pref("a", 1);') is None
    assert ft._pref_key('pref("a", 1);') is None


def test_merge_user_js_replaces_a_single_quoted_managed_line(tmp_path: Path) -> None:
    user_js = tmp_path / "user.js"
    user_js.write_text("user_pref('ui.systemUsesDarkTheme', 0);\n")
    ft.merge_user_js(user_js, {"ui.systemUsesDarkTheme": 1})
    assert user_js.read_text() == 'user_pref("ui.systemUsesDarkTheme", 1);\n'


def test_merge_user_js_keeps_the_users_inline_comment(tmp_path: Path) -> None:
    user_js = tmp_path / "user.js"
    user_js.write_text(
        'user_pref("ui.systemUsesDarkTheme", 0); // set by hand\n'
        'user_pref("extensions.activeThemeID", "default-theme@mozilla.org"); /* was */\n'
        'user_pref("keep.me", "a); b"); // tricky value\n'
    )
    ft.merge_user_js(user_js, {"ui.systemUsesDarkTheme": 1, "extensions.activeThemeID": "x@y"})
    assert user_js.read_text() == (
        'user_pref("ui.systemUsesDarkTheme", 1); // set by hand\n'
        'user_pref("extensions.activeThemeID", "x@y"); /* was */\n'
        'user_pref("keep.me", "a); b"); // tricky value\n'
    )


def test_merge_user_js_drops_later_duplicates_of_a_managed_key(tmp_path: Path) -> None:
    user_js = tmp_path / "user.js"
    user_js.write_text(
        'user_pref("ui.systemUsesDarkTheme", 0); // first\n'
        "// between\n"
        "user_pref('ui.systemUsesDarkTheme', 0);\n"
    )
    ft.merge_user_js(user_js, {"ui.systemUsesDarkTheme": 1})
    assert user_js.read_text() == 'user_pref("ui.systemUsesDarkTheme", 1); // first\n// between\n'


def test_merge_user_js_preserves_crlf_line_endings(tmp_path: Path) -> None:
    user_js = tmp_path / "user.js"
    user_js.write_bytes(b'// mine\r\nuser_pref("ui.systemUsesDarkTheme", 0);\r\n')
    assert ft.merge_user_js(user_js, {"ui.systemUsesDarkTheme": 1, "x.y": True}) is True
    assert user_js.read_bytes() == (
        b'// mine\r\nuser_pref("ui.systemUsesDarkTheme", 1);\r\nuser_pref("x.y", true);\r\n'
    )
    # And a second run is a byte-for-byte no-op, CRLF included.
    assert ft.merge_user_js(user_js, {"ui.systemUsesDarkTheme": 1, "x.y": True}) is False
    assert b"\r\n" in user_js.read_bytes() and b"\n\n" not in user_js.read_bytes()


def test_non_utf8_profiles_ini_yields_no_profiles_instead_of_crashing(tmp_path: Path) -> None:
    """A latin-1 profile Name is not a configparser.Error: uncaught, the
    UnicodeDecodeError killed theming for every browser and --status with it."""
    ini = tmp_path / "profiles.ini"
    ini.write_bytes(b"[Profile0]\nName=caf\xe9\nPath=p0\nDefault=1\n")
    assert ft.default_profiles(ini) == []


def test_merge_user_js_round_trips_non_utf8_bytes(tmp_path: Path) -> None:
    """A user-edited line with a latin-1 comment must neither crash the merge
    (an unhandled UnicodeDecodeError used to kill theming for the profile)
    nor be rewritten: surrogateescape round-trips the bytes exactly."""
    user_js = tmp_path / "user.js"
    user_js.write_bytes(b'// caf\xe9 config\nuser_pref("keep.me", 1);\n')
    assert ft.merge_user_js(user_js, {"ui.systemUsesDarkTheme": 1}) is True
    assert user_js.read_bytes() == (
        b'// caf\xe9 config\nuser_pref("keep.me", 1);\nuser_pref("ui.systemUsesDarkTheme", 1);\n'
    )
    assert ft.merge_user_js(user_js, {"ui.systemUsesDarkTheme": 1}) is False
    # The --status path reads the same file and must not crash either.
    assert ft._pref_key_present(user_js, "keep.me") is True


def test_merge_user_js_splits_on_real_line_terminators_only(tmp_path: Path) -> None:
    """str.splitlines() also breaks on U+0085, U+2028/9, \\x0b, \\x0c,
    \\x1c-\\x1e and a lone \\r, so a valid UTF-8 comment or pref value carrying
    one came back rewritten with a newline (a value split that way is an
    unterminated string literal — the user's own pref lost). Only LF and
    CRLF delimit lines: everything else round-trips byte-for-byte, a
    managed line's inline comment included, the re-run is a no-op, and
    --status still reads the keys and values in such lines."""
    user_js = tmp_path / "user.js"
    kept = (
        "// see\u0085also, a\u2028b, a\u2029c\n"
        "// page\x0cbreak\x0bvt\x1c\x1d\x1e cr\rhere\n"
        'user_pref("keep.me", "a\u2028b\u0085c");\n'
    )
    managed = 'user_pref("ui.systemUsesDarkTheme", %d); // was\u2028here\n'
    user_js.write_bytes((kept + managed % 0).encode())
    assert ft.merge_user_js(user_js, {"ui.systemUsesDarkTheme": 1}) is True
    assert user_js.read_bytes() == (kept + managed % 1).encode()
    assert ft.merge_user_js(user_js, {"ui.systemUsesDarkTheme": 1}) is False
    assert ft._pref_key_present(user_js, "keep.me") is True
    assert ft._pref_value(user_js, "keep.me") == "a\u2028b\u0085c"


def test_writes_go_through_the_link_and_never_truncate_in_place(tmp_path: Path) -> None:
    """user.js is the user's own and Firefox never regenerates it, so the
    bytes are written beside the target and renamed over it — through the
    link, so a dotfile manager's symlinked user.js keeps its link and its
    target gets the prefs; the file's mode is kept, a new file gets the
    umask's (as a plain open() would), no temp file is left behind, and an
    unchanged file is not rewritten at all."""
    dotfiles = tmp_path / "dotfiles"
    dotfiles.mkdir()
    target = dotfiles / "user.js"
    target.write_bytes(b'user_pref("keep.me", 1);\n')
    target.chmod(0o600)
    profile = tmp_path / "profile"
    profile.mkdir()
    link = profile / "user.js"
    link.symlink_to(target)
    assert ft.merge_user_js(link, {"ui.systemUsesDarkTheme": 1}) is True
    assert link.is_symlink() and link.resolve() == target
    assert target.read_bytes() == (
        b'user_pref("keep.me", 1);\nuser_pref("ui.systemUsesDarkTheme", 1);\n'
    )
    assert stat.S_IMODE(target.stat().st_mode) == 0o600
    assert [p.name for p in dotfiles.iterdir()] == ["user.js"]
    assert [p.name for p in profile.iterdir()] == ["user.js"]
    before = target.stat()
    assert ft.merge_user_js(link, {"ui.systemUsesDarkTheme": 1}) is False
    after = target.stat()
    assert (after.st_ino, after.st_mtime_ns) == (before.st_ino, before.st_mtime_ns)
    # A file written from nothing: the kernel applies the umask, as for open().
    old = os.umask(0o022)
    try:
        assert ft.apply(profile, CSS_DARK) is True
    finally:
        os.umask(old)
    assert stat.S_IMODE((profile / "chrome" / "userChrome.css").stat().st_mode) == 0o644


def test_a_failed_write_leaves_the_original_and_no_temp_file(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A crash or a full disk between the old truncate and the write left an
    empty user.js and Firefox without the user's prefs; now the rename is
    the only step that touches it, and a write that dies before it leaves
    the original as it was and no temp file beside it."""
    profile = tmp_path / "profile"
    profile.mkdir()
    user_js = profile / "user.js"
    raw = b'user_pref("keep.me", 1);\n'
    user_js.write_bytes(raw)

    def full_disk(_fd: int) -> None:
        raise OSError(errno.ENOSPC, "No space left on device")

    monkeypatch.setattr(ft.os, "fsync", full_disk)
    with pytest.raises(OSError):
        ft.merge_user_js(user_js, {"ui.systemUsesDarkTheme": 1})
    assert user_js.read_bytes() == raw
    assert [p.name for p in profile.iterdir()] == ["user.js"]


# ---------------------------------------------------------------------------
# apply + main: the rendered file into the profiles
# ---------------------------------------------------------------------------


def test_apply_copies_the_rendered_file_byte_for_byte_and_is_idempotent(
    hermetic: dict[str, Path],
) -> None:
    profile = _profile(hermetic)
    assert ft.apply(profile, CSS_DARK) is True
    assert (profile / "chrome" / "userChrome.css").read_bytes() == CSS_DARK
    js = (profile / "user.js").read_text()
    assert 'user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);' in js
    assert 'user_pref("ui.systemUsesDarkTheme", 1);' in js
    assert f'user_pref("extensions.activeThemeID", "{ft.THEME_ID_DARK}");' in js

    assert ft.apply(profile, CSS_DARK) is False  # nothing to rewrite, nothing to announce
    assert (profile / "chrome" / "userChrome.css").read_bytes() == CSS_DARK
    assert (profile / "user.js").read_text() == js
    # A re-render (new theme) is a change again.
    assert ft.apply(profile, CSS_LIGHT) is True
    assert (profile / "chrome" / "userChrome.css").read_bytes() == CSS_LIGHT


def test_main_copies_into_every_installs_profile_and_announces_the_browser_once(
    hermetic: dict[str, Path], capsys: pytest.CaptureFixture[str], notices: list[str]
) -> None:
    _theme(hermetic)
    release, dev = _two_install_profiles(hermetic)
    assert ft.main([]) == 0
    for profile in (release, dev):
        assert (profile / "chrome" / "userChrome.css").read_bytes() == CSS_DARK
        assert ft.THEME_ID_DARK in (profile / "user.js").read_text()
    out = capsys.readouterr().out
    assert out.count("firefox: ") == 2 and "restart firefox" in out.lower()
    # Nothing of Omarchy's theme machinery runs from here.
    assert hermetic["calls"].read_text() == ""
    # Firefox reads userChrome.css at startup only: the change is announced
    # once, through Omarchy's notification command, and not on a no-op re-run.
    assert notices == ["Restart firefox to apply the new theme"]
    assert ft.main([]) == 0
    assert len(notices) == 1


def test_light_theme_gets_the_light_prefs(hermetic: dict[str, Path]) -> None:
    _theme(hermetic, rendered=CSS_LIGHT)
    profile = _profile(hermetic)
    (profile / "user.js").write_text('user_pref("keep.me", 1);\n')
    assert ft.main([]) == 0
    js = (profile / "user.js").read_text()
    assert f'user_pref("extensions.activeThemeID", "{ft.THEME_ID_LIGHT}");' in js
    assert 'user_pref("ui.systemUsesDarkTheme", 0);' in js
    assert 'user_pref("keep.me", 1);' in js


def test_missing_rendered_file_is_an_error_and_nothing_is_rendered_here(
    hermetic: dict[str, Path], capsys: pytest.CaptureFixture[str]
) -> None:
    """Rendering is Omarchy's alone: omarchy-theme-set leaves every rendered
    template in current/theme (omarchy-theme-set-templates, then the
    staging-dir mv in omarchy-theme-set) and stage_themed
    re-renders through omarchy-theme-refresh, so a missing file means no
    theme, no template installed, or a failed refresh. The bridge names the
    file and `omarchy theme refresh`, exits non-zero, runs none of Omarchy's
    theme commands (the stubs would record it) and leaves the profile
    untouched — with a theme active, and with none at all."""
    theme = _theme(hermetic, rendered=None)
    profile = _profile(hermetic)
    assert ft.main([]) == 1
    err = capsys.readouterr().err
    assert str(theme / "userChrome.css") in err and "omarchy theme refresh" in err
    assert not (profile / "chrome").exists() and not (profile / "user.js").exists()
    (theme / "colors.toml").unlink()
    assert ft.main([]) == 1
    assert "userChrome.css" in capsys.readouterr().err
    assert hermetic["calls"].read_text() == ""


def test_main_without_a_profile_is_a_noop(
    hermetic: dict[str, Path], capsys: pytest.CaptureFixture[str]
) -> None:
    _theme(hermetic)
    assert ft.main([]) == 0
    assert "nothing to do" in capsys.readouterr().out


# ---------------------------------------------------------------------------
# --status: the source, the copies, and "has Firefox restarted?" from prefs.js
# ---------------------------------------------------------------------------


def test_status_reports_the_source_and_the_restart_state(
    hermetic: dict[str, Path], capsys: pytest.CaptureFixture[str]
) -> None:
    theme = _theme(hermetic)
    profile = _profile(hermetic)
    assert ft.main([]) == 0
    capsys.readouterr()

    # Firefox has not been restarted: prefs.js still names the default theme.
    (profile / "prefs.js").write_text(
        'user_pref("extensions.activeThemeID", "default-theme@mozilla.org");\n'
    )
    assert ft.main(["--status"]) == 0
    out = capsys.readouterr().out
    assert f"rendered: {theme / 'userChrome.css'} (dark)" in out
    assert "userChrome.css: written" in out
    assert "3/3 managed prefs present" in out
    assert "restarted since the files were written: NO" in out

    # After a restart Firefox writes the theme it activated from user.js.
    (profile / "prefs.js").write_text(
        f'user_pref("extensions.activeThemeID", "{ft.THEME_ID_DARK}");\n'
    )
    assert ft.main(["--status"]) == 0
    assert "restarted since the files were written: yes" in capsys.readouterr().out

    # A theme set since (new rendered file, hook not yet run) shows as stale.
    (theme / "userChrome.css").write_bytes(CSS_LIGHT)
    assert ft.main(["--status"]) == 0
    out = capsys.readouterr().out
    assert "(light)" in out and "userChrome.css: STALE" in out


def test_status_reports_every_installs_profile(
    hermetic: dict[str, Path], capsys: pytest.CaptureFixture[str]
) -> None:
    _theme(hermetic)
    release, dev = _two_install_profiles(hermetic)
    assert ft.main(["--status"]) == 0
    out = capsys.readouterr().out
    assert f"firefox: profile {release}" in out and f"firefox: profile {dev}" in out
    assert out.count("userChrome.css: MISSING") == 2
    assert out.count("0/3 managed prefs present") == 2


def test_status_without_a_profile_or_rendered_file_still_exits_zero(
    hermetic: dict[str, Path], capsys: pytest.CaptureFixture[str]
) -> None:
    assert ft.main(["--status"]) == 0
    out = capsys.readouterr().out
    assert "rendered: MISSING" in out and "no Firefox/LibreWolf profile" in out


# ---------------------------------------------------------------------------
# The template Omarchy renders, and the hook that runs all this
# ---------------------------------------------------------------------------


def _sed_render(tpl: str, palette: dict[str, str]) -> str:
    """bin/omarchy-theme-set-templates:195-207 (add_template_value) in Python:
    `{{ key }}`, `{{ key_strip }}` and, for a 6-digit hex, `{{ key_rgb }}`."""
    out = tpl
    for key, value in palette.items():
        out = out.replace("{{ " + key + " }}", value)
        out = out.replace("{{ " + key + "_strip }}", value.lstrip("#"))
        if re.fullmatch(r"#[0-9A-Fa-f]{6}", value):
            rgb = ",".join(str(int(value[i : i + 2], 16)) for i in (1, 3, 5))
            out = out.replace("{{ " + key + "_rgb }}", rgb)
    return out


def test_template_renders_the_firefox_variables_and_selectors() -> None:
    """The template is the whole palette now: it must use only keys
    omarchy-theme-color resolves for every theme (bin/omarchy-theme-color
    :176-281 — background, foreground, accent, dark_background,
    lighter_background, mode), declare the mode firefox_theme reads back, and
    render every variable and selector asserted below."""
    tpl = TEMPLATE.read_text()
    assert tpl.startswith("/* Generated by hyprconf from Omarchy's active theme")
    tokens = set(re.findall(r"\{\{\s*([A-Za-z0-9_]+)\s*\}\}", tpl))
    assert tokens == {
        "mode",
        "background",
        "foreground",
        "accent",
        "dark_background",
        "lighter_background",
    }

    css = _sed_render(tpl, PALETTE)
    assert "{{" not in css and css.count("{") == css.count("}")
    assert ft.rendered_mode(css.encode()) == "dark"
    assert ft.rendered_mode(_sed_render(tpl, {**PALETTE, "mode": "light"}).encode()) == "light"
    for line in (
        "--hyprconf-theme-mode: dark;",
        "--lwt-accent-color: #16242d !important;",
        "--lwt-text-color: #d6e2ee !important;",
        "--toolbar-bgcolor: #16242d !important;",
        "--toolbar-color: #d6e2ee !important;",
        "--tab-selected-bgcolor: #1b2d40 !important;",
        "--toolbar-field-background-color: #101b21 !important;",
        "--toolbar-field-color: #d6e2ee !important;",
        "--toolbar-field-focus-background-color: #101b21 !important;",
        "--toolbar-field-focus-color: #d6e2ee !important;",
        "--lwt-sidebar-background-color: #16242d !important;",
        "--lwt-sidebar-text-color: #d6e2ee !important;",
        "--focus-outline-color: #8bc9eb !important;",
        # Direct chrome selectors too, so the colours hold under any active theme.
        "#navigator-toolbox, #TabsToolbar, #nav-bar, #PersonalToolbar {",
        "#urlbar-background, #searchbar {",
        ".tab-background[selected] {",
        "#sidebar-box, #sidebar-main {",
    ):
        assert line in css, line
    # The direct rules (indented declarations, not the --*-background-color
    # variables): toolbox + sidebar, URL bar + search, selected tab.
    assert css.count("\n  background-color: #16242d !important;") == 2
    assert css.count("\n  background-color: #101b21 !important;") == 1
    assert css.count("\n  background-color: #1b2d40 !important;") == 1


def _installed_hook(tmp_path: Path) -> Path:
    """The hook as install.sh's stage_hooks writes it: @HYPRCONF_DIR@ resolved."""
    hook = tmp_path / "10-hyprconf"
    hook.write_text(HOOK.read_text().replace("@HYPRCONF_DIR@", str(REPO_ROOT)))
    return hook


def _run_hook(hermetic: dict[str, Path], hook: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["bash", str(hook), "lumon"],
        capture_output=True,
        text=True,
        timeout=60,
        env={"HOME": str(hermetic["home"]), "PATH": f"{hermetic['bins']}:/usr/bin:/bin"},
    )


def test_theme_set_hook_runs_the_firefox_bridge_and_only_that(
    tmp_path: Path, hermetic: dict[str, Path]
) -> None:
    """The hook runs the bridge and nothing else (VS Code is themed by
    Omarchy's own omarchy-theme-set-vscode); it must not abort a theme switch
    (no set -e) and must never escalate."""
    code = "\n".join(
        line for line in HOOK.read_text().splitlines() if not line.lstrip().startswith("#")
    )
    for forbidden in ("set -e", "sudo"):
        assert forbidden not in code, forbidden
    assert "hyprconf.firefox_theme" in code

    _theme(hermetic)
    (hermetic["bins"] / "omarchy-notification-send").write_text("#!/usr/bin/env bash\nexit 0\n")
    (hermetic["bins"] / "omarchy-notification-send").chmod(0o755)
    profile = _profile(hermetic)
    proc = _run_hook(hermetic, _installed_hook(tmp_path))
    assert proc.returncode == 0, proc.stderr
    assert (profile / "chrome" / "userChrome.css").read_bytes() == CSS_DARK
    assert ft.THEME_ID_DARK in (profile / "user.js").read_text()
    assert "failed" not in proc.stderr


def test_theme_set_hook_never_fails_the_theme_switch(
    tmp_path: Path, hermetic: dict[str, Path]
) -> None:
    """No rendered file: the bridge exits non-zero, the hook says so on stderr
    and still exits 0 — omarchy-hook must never see an abort — and it never
    re-enters the theme machinery it runs inside of."""
    _theme(hermetic, rendered=None)
    _profile(hermetic)
    proc = _run_hook(hermetic, _installed_hook(tmp_path))
    assert proc.returncode == 0
    assert "Firefox theming failed" in proc.stderr and "userChrome.css" in proc.stderr
    assert hermetic["calls"].read_text() == ""
